### ISSUE TITLE
Get 9500 node model in Survalent (CIM Importer)

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1029]
Need UML file from Eric

Need a resource: Java, SPARQL , UML (S&E 3 or 4) for 4 weeks may be more.
Jonathan may have someone.

**Comment by temcdrm** [comment]
Sent a candidate file for the 123-bus PV system to Survalent on 8/22.  Survalent will take a look this coming week.

**Comment by temcdrm** [comment]
Survalent is part of the EPRI Grid Model Data Management (GMDM) project, slated to participate in a CIM interop in May, 2022. The main test circuit will be a demonstration model from ESRI, so they don't need a 123-bus or 9500-node model from PNNL.

We'll most likely be helping Survalent and other participants with CIM examples for this upcoming interop.
