### ISSUE TITLE
Clarification on the need for multiple DisclosureResponse classes 

### ISSUE THREAD

**Issue by ericstephan** [GRIDAPPSD/GOSS-GridAPPS-D#1063]
![image.png]### Description of Issue

Hi Todd,

I’m still in the process of merging the RepositoryResource class when I ran into a situation where there are multiple instances of DisclosureResponse in the disclosure lib, disclosure module and hybrid module packages.   From your original code I am using the class from the disclosure lib package, but it appears that this is deprecated.  

How do these different DisclosureResponse classes work and how are we supposed to use them?

Thanks,

Eric

**Comment by telsethag** [comment]
Hi Eric,

Sorry about the confusion.  There are two _DisclosureResponse_ types located in the following packages:

1.  _gov.pnnl.proven.cluster.lib.disclosure.messge_
2.  _gov.pnnl.proven.cluster.module.hybrid.message_

(2) was created to support JMS and is not being used.  It and associated types should probably be removed.

(1) has been deprecated in favor of _gov.pnnl.proven.cluster.lib.disclosure.message.ResponseMessage_  .  We should remove/replace occurrences of (1) with _ResponseMessage_.

**Comment by telsethag** [comment]
Re-opening this issue.

Refactor DisclosureResponse to ResponseMessage as part of TSService pipeline #792 in Proven 2.0 release.
