### ISSUE TITLE
Low Voltages on the 9500-Node System

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#1068]
The 9500-node system now has voltages as low as 0.86 perunit in OpenDSS, i.e., before the CIM export.  This complicates the conversion and validation process, because of the extra solution iterations needed. Please revise the baseline model so it exhibits normal voltages.  The abnormal conditions can be scripted once the baseline model has been loaded.

Shiva and Alexander should be assigned this issue, but I can't find them in the list of Assignees.

**Comment by poorva1209** [comment]
@temcdrm Is this issue still relevant ?

**Comment by shpoudel** [comment]
I think the voltages are around 0.93 p.u. in OpenDSS in the current version.

**Comment by poorva1209** [comment]
Closing. Not relevant anymore.
