### ISSUE TITLE
Publish alarm on message bus

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1087]
Publish Alarm: Switch Opened.
Differentiate between switch open command from UI vs Test Manager.

Define what alarms are, model, API.  
Can look at Survalent system. 

@shpoudel -  Provide requirements.

**Comment by shpoudel** [comment]
@poorva1209 and  @afisher1 The requirement for differentiating between operator command and actual fault would be something like following:

Switch Status – 0/1 (indicating whether the status is open or closed)

Alarm Status – 0/1 (1 – indicating an operator action and that the application should not do anything; 0 – indicating no alarm and if switch status changes restoration application should act). 

Note: An Operator should initiate an alarm if they change the switch status for some reason.

The requirement is we just need to an additional attribute with the switch: "Alarm Status" in addition to it's open/close status.
