### ISSUE TITLE
Release current version of GOSS

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#11]
- new branch
- publish on repo

**Comment by craig8** [comment]
As of https://github.com/GridOPTICS/GOSS/pull/13 we can now use the reporepository that is in the cnf directory.

To do so add
````
aQute.bnd.deployer.repository.FixedIndexedRepo; name=GOSS Core;   locations=https://raw.githubusercontent.com/GridOPTICS/GOSS/master/cnf/releaserepo/index.xml
````
To your cnf/ext/repositories.bnd file.
