### ISSUE TITLE
Insert load profile in influxdb and create variable load player file for each simulation

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1103]
- [ ] App should be able to ask for loaf profile info for model

**Comment by ericstephan** [comment]
@afisher1 I didn't receive an attachment in your email.

**Comment by ericstephan** [comment]
Got it, thank you @afisher1

**Comment by ericstephan** [comment]
@afisher1 I finished the preliminary script and will be testing it loading into the database tonight..

Here is a small snapshot of the loadprofiles measurement:  From the data you provided me I created a year's worth of data repeating over a 24 hour period.  Let me know if you see anything I've missed.

loadprofiles,DATE='29/12/2018',UTC='22:56' value=0.424510 1546152960
loadprofiles,DATE='29/12/2018',UTC='22:57' value=0.431012 1546153020
loadprofiles,DATE='29/12/2018',UTC='22:58' value=0.426154 1546153080
loadprofiles,DATE='29/12/2018',UTC='22:59' value=0.427149 1546153140
loadprofiles,DATE='29/12/2018',UTC='23:00' value=0.425364 1546153200
loadprofiles,DATE='29/12/2018',UTC='23:01' value=0.421530 1546153260
loadprofiles,DATE='29/12/2018',UTC='23:02' value=0.418488 1546153320
loadprofiles,DATE='29/12/2018',UTC='23:03' value=0.399880 1546153380
loadprofiles,DATE='29/12/2018',UTC='23:04' value=0.382085 1546153440
loadprofiles,DATE='29/12/2018',UTC='23:05' value=0.366393 1546153500
loadprofiles,DATE='29/12/2018',UTC='23:06' value=0.352824 1546153560
loadprofiles,DATE='29/12/2018',UTC='23:07' value=0.340989 1546153620
loadprofiles,DATE='29/12/2018',UTC='23:08' value=0.332697 1546153680
loadprofiles,DATE='29/12/2018',UTC='23:09' value=0.325956 1546153740
loadprofiles,DATE='29/12/2018',UTC='23:10' value=0.318178 1546153800
loadprofiles,DATE='29/12/2018',UTC='23:11' value=0.312444 1546153860
loadprofiles,DATE='29/12/2018',UTC='23:12' value=0.309558 1546153920
loadprofiles,DATE='29/12/2018',UTC='23:13' value=0.310901 1546153980
loadprofiles,DATE='29/12/2018',UTC='23:14' value=0.311296 1546154040
loadprofiles,DATE='29/12/2018',UTC='23:15' value=0.306408 1546154100
loadprofiles,DATE='29/12/2018',UTC='23:16' value=0.304770 1546154160
loadprofiles,DATE='29/12/2018',UTC='23:17' value=0.302977 1546154220
loadprofiles,DATE='29/12/2018',UTC='23:18' value=0.302303 1546154280
loadprofiles,DATE='29/12/2018',UTC='23:19' value=0.303205 1546154340
loadprofiles,DATE='29/12/2018',UTC='23:20' value=0.304910 1546154400
loadprofiles,DATE='29/12/2018',UTC='23:21' value=0.306217 1546154460
loadprofiles,DATE='29/12/2018',UTC='23:22' value=0.301342 1546154520
loadprofiles,DATE='29/12/2018',UTC='23:23' value=0.301985 1546154580
loadprofiles,DATE='29/12/2018',UTC='23:24' value=0.301002 1546154640
loadprofiles,DATE='29/12/2018',UTC='23:25' value=0.299018 1546154700
loadprofiles,DATE='29/12/2018',UTC='23:26' value=0.299475 1546154760
loadprofiles,DATE='29/12/2018',UTC='23:27' value=0.298758 1546154820
loadprofiles,DATE='29/12/2018',UTC='23:28' value=0.299517 1546154880
loadprofiles,DATE='29/12/2018',UTC='23:29' value=0.300090 1546154940
loadprofiles,DATE='29/12/2018',UTC='23:30' value=0.301226 1546155000
loadprofiles,DATE='29/12/2018',UTC='23:31' value=0.296975 1546155060
loadprofiles,DATE='29/12/2018',UTC='23:32' value=0.297793 1546155120
loadprofiles,DATE='29/12/2018',UTC='23:33' value=0.297055 1546155180
loadprofiles,DATE='29/12/2018',UTC='23:34' value=0.297666 1546155240
loadprofiles,DATE='29/12/2018',UTC='23:35' value=0.297606 1546155300
loadprofiles,DATE='29/12/2018',UTC='23:36' value=0.295814 1546155360
loadprofiles,DATE='29/12/2018',UTC='23:37' value=0.295908 1546155420
loadprofiles,DATE='29/12/2018',UTC='23:38' value=0.297136 1546155480
loadprofiles,DATE='29/12/2018',UTC='23:39' value=0.295663 1546155540
loadprofiles,DATE='29/12/2018',UTC='23:40' value=0.296913 1546155600
loadprofiles,DATE='29/12/2018',UTC='23:41' value=0.294364 1546155660
loadprofiles,DATE='29/12/2018',UTC='23:42' value=0.294672 1546155720
loadprofiles,DATE='29/12/2018',UTC='23:43' value=0.294449 1546155780
loadprofiles,DATE='29/12/2018',UTC='23:44' value=0.293077 1546155840
loadprofiles,DATE='29/12/2018',UTC='23:45' value=0.294809 1546155900
loadprofiles,DATE='29/12/2018',UTC='23:46' value=0.293339 1546155960
loadprofiles,DATE='29/12/2018',UTC='23:47' value=0.294001 1546156020
loadprofiles,DATE='29/12/2018',UTC='23:48' value=0.293465 1546156080
loadprofiles,DATE='29/12/2018',UTC='23:49' value=0.295438 1546156140
loadprofiles,DATE='29/12/2018',UTC='23:50' value=0.294657 1546156200
loadprofiles,DATE='29/12/2018',UTC='23:51' value=0.292661 1546156260
loadprofiles,DATE='29/12/2018',UTC='23:52' value=0.293831 1546156320
loadprofiles,DATE='29/12/2018',UTC='23:53' value=0.292585 1546156380
loadprofiles,DATE='29/12/2018',UTC='23:54' value=0.293295 1546156440
loadprofiles,DATE='29/12/2018',UTC='23:55' value=0.293815 1546156500
loadprofiles,DATE='29/12/2018',UTC='23:56' value=0.293870 1546156560
loadprofiles,DATE='29/12/2018',UTC='23:57' value=0.292995 1546156620
loadprofiles,DATE='29/12/2018',UTC='23:58' value=0.293847 1546156680
loadprofiles,DATE='29/12/2018',UTC='23:59' value=0.290652 1546156740

**Comment by poorva1209** [comment]
@ericstephan Make sure the timestamp and timezone align with those in weather. @tonya1 can help with that.

**Comment by ericstephan** [comment]
the epoch timestamp is derived from the  DATE and UTC fields @poorva1209 let me know if there is problem.

**Comment by ericstephan** [comment]
@afisher1 @poorva1209 @tonya1 @craig8 - the docker image of influx was not doing well when I loaded the loadprofiles data for 365x24x60 minutes of data.  I tested a standalone copy of influx I downloaded with Homebrew on my mac and didn't observe this instability.  

This is something I want to look into further to see what might be going on...

One aspect about this is that I couldn't use the same bulk load technique that I did with the weather data, so I'm using the influx rest service and making 365 separate batch calls.  The data is imported, but attempting to query data from the measurement results in the docker image shutting down.  This batch technique I'm using relies on the influx rest client.  I tried putting in a five second time delay every one hundred batches and waiting time after the load to attempt querying.  Even after restarting the influx docker image I still cannot perform simple queries against loadprofile.

One area I may look into is attempting the old technique with the create database DDL command to see if is robust enough to ignore the create failure and load the data anyway.

**Comment by ericstephan** [comment]
@afisher1 I did provide @poorva1209 a one day sample set that she is working with while I chase down the large ingest problem.  I can provide you all the data if you'd like to experiment with a day of your choice so that this does not block your needs.    

I also noticed in the UTC and DATE fields that there are single quotes around the text.  If this is getting in the way I can try to find a way of removing this.

**Comment by ericstephan** [comment]
A new script has been introduced in the develop branch to support loading profiles.  Look under the time-series/loadprofile directory in:

https://github.com/GRIDAPPSD/gridappsd-data/tree/develop

**Comment by ericstephan** [comment]
The following changes were checked in:
* All tags were removed.
* The epoch time was corrected to start at January 1, 2018 00:00:00 UTC and increment 1 minute for one year.

**Comment by ericstephan** [comment]
@poorva1209  and @tonya1 please review.

**Comment by poorva1209** [comment]
Re-opening this as updated data in influxdb is one part of this issue. 
@tonya1 Create updated influxdb container. 

I will create a request handler for this data that will create a load file for he simulation.

**Comment by tonya1** [comment]
@poorva1209 Updated docker container has been pushed to dockerhub for testing 
gridappsd/influxdb:loadprofile

**Comment by poorva1209** [comment]
> @poorva1209 Updated docker container has been pushed to dockerhub for testing
> gridappsd/influxdb:loadprofile

@tonya1 : I dont see loadprofile data in gridappsd/influxdb:loadprofile container. Do you see it ?

**Comment by ericstephan** [comment]
Let me know if you need help, I’m out of meetings now. @poorva1209 @tonya1
