### ISSUE TITLE
Start OpenDSS with GridLAB-D for houses

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1108]

**Comment by temcdrm** [comment]
GridLAB-D work has been done here: [https://github.com/gridlab-d/gridlab-d/pull/1251](url)

**Comment by poorva1209** [comment]
Frank need to merge the pull request on gridlab-d

**Comment by temcdrm** [comment]
This pull request was closed on GridLAB-D: https://github.com/gridlab-d/gridlab-d/pull/1273 and it encapsulates https://github.com/gridlab-d/gridlab-d/pull/1251
