### ISSUE TITLE
3-phase transformer voltages  - primary_1 and secondary_1 should be line to line

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1120]
- it can cause lower voltages 
- mainly for commercial transformers

**Comment by temcdrm** [comment]
Please use LoadXfmrCodes.dss instead of LoadXfmrs.dss from the original EPRI version. This results in sharing of transformer nameplate data, which translates to smaller CIM XML files, smaller GLM files and less time to generate the model when the platform starts a simulation.
