### ISSUE TITLE
DSS files are not loading transformer codes

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1121]
- easy fix

**Comment by temcdrm** [comment]
Just tested and pushed the fix to "develop" branch on powergrid-models.  There is a new LoadXfmrCodes.dss file, which first defines the 9 different types of transformer used:

New XfmrCode.CT5   phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[  5.0   5.0   5.0] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36
New XfmrCode.CT10  phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[ 10.0  10.0  10.0] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36
New XfmrCode.CT15  phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[ 15.0  15.0  15.0] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36
New XfmrCode.CT25  phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[ 25.0  25.0  25.0] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36
New XfmrCode.CT37  phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[ 37.5  37.5  37.5] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36
New XfmrCode.CT50  phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[ 50.0  50.0  50.0] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36
New XfmrCode.CT75  phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[ 75.0  75.0  75.0] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36
New XfmrCode.CT100 phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[100.0 100.0 100.0] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36
New XfmrCode.CT250 phases=1 windings=3 kvs=[7.2 0.12 0.12] kVAs=[250.0 250.0 250.0] %imag=0.5 %Rs=[0.6 1.2 1.2] %noloadloss=.2 Xhl=2.04  Xht=2.04  Xlt=1.36

The rest of the file contains the original EPRI 8500-node transformers, plus those added for the 9500-node model.  A sample is shown below:

New Transformer.T2001400C         XfmrCode=CT75    buses=[M2001400.3 X2001400C.1.0 X2001400C.0.2]

The syntax is more concise on the OpenDSS side, and helps to enforce consistent parameter values.  In GridAPPS-D, the resulting XML and GLM files are about 80% as large as they were before.  The number of object instances is also smaller, which reduces complexity of the model queries and generation.

**Comment by poorva1209** [comment]
@tonya1 : You need to create a new blazegraph container based on these new files.

**Comment by poorva1209** [comment]
@temcdrm I am re-opening this issue and moving it in review until we have these model changes in blazegraph and test them with a simulation.

**Comment by tonya1** [comment]
@poorva1209 gridappsd/blazegraph:112 has been pushed to dockerhub
