### ISSUE TITLE
Error when attempting to include multiple values in a time series data manager request.

### ISSUE THREAD

**Issue by ericstephan** [GRIDAPPSD/GOSS-GridAPPS-D#1129]
### Description of Issue
In Stomp when the following query is attempted using the time series data manager, I get an error about an illegal array structure in the message.  

{
	"queryType": "time-series",
	"queryMeasurement": "simulation",
	"queryFilter": {
		"measurement_mrid": [
			"_001bff93-9a98-45ab-a099-f64f49f0ce1b",
			"_17c904dc-7788-4a6f-9083-20f4e06bded3"
		]
	},
	"responseFormat": "csv"
}

    "error": {
        "message": "com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 96 path $.queryFilter.\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:200)\n\tat com.google.gson.Gson.fromJson(Gson.java:810)\n\tat com.google.gson.Gson.fromJson(Gson.java:775)\n\tat com.google.gson.Gson.fromJson(Gson.java:724)\n\tat com.google.gson.Gson.fromJson(Gson.java:696)\n\tat gov.pnnl.goss.gridappsd.dto.RequestTimeseriesData.parse(RequestTimeseriesData.java:53)\n\tat gov.pnnl.goss.gridappsd.data.ProvenTimeSeriesDataManagerImpl.handle(ProvenTimeSeriesDataManagerImpl.java:111)\n\tat gov.pnnl.goss.gridappsd.data.DataManagerImpl.processDataRequest(DataManagerImpl.java:149)\n\tat gov.pnnl.goss.gridappsd.process.ProcessEvent.onMessage(ProcessEvent.java:213)\n\tat pnnl.goss.core.client.GossClient$1.run(GossClient.java:321)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 96 path $.queryFilter.\n\tat com.google.gson.stream.JsonReader.nextString(JsonReader.java:837)\n\tat com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:358)\n\tat com.google.gson.internal.bind.TypeAdapters$13.read(TypeAdapters.java:346)\n\tat com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)\n\tat com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:187)\n\tat com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)\n\tat com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)\n\t... 10 more\n"
    },
    "responseComplete": true,
    "id": "787cd9a8-77fe-4651-9c3e-fa0f6faaad3f"

### Affected Version

This should work in the development branch.  I'm attempting to test code to support multiple values, but I can't seem to get past this error.

**Comment by poorva1209** [comment]
@ericstephan 
Develop branch does not have changes to support multiple mrid query. 
I made the changes in a saperate branch and created this pull request: https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/1130
Please test it with Proven before merging. I am using proven: develop tag where multiple mrid query did not work and also I am not getting results back in CSV. We can debug csv issue once multiple mrids are done.

**Comment by ericstephan** [comment]
The following master branch supports the new style query in release v1.3.5.10 https://github.com/pnnl/proven-cluster/releases/tag/v1.3.5.10
