### ISSUE TITLE
Viz doesn't stop bouncing balls if faster than real time

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#1142]
![image](https://user-images.githubusercontent.com/3979063/67445668-8c6e2500-f5c2-11e9-95d2-7ebf28468d8d.png)

**Comment by poorva1209** [comment]
@bibiraju @nhuyvan Let's discuss what Viz should display for faster than real-time during work meeting today.

**Comment by nhuyvan** [comment]
@poorva1209 I have class today from 12 - 1:15, so I won't be able to attend

**Comment by poorva1209** [comment]
> @poorva1209 I have class today from 12 - 1:15, so I won't be able to attend

That's okay we can talk afterward.
