### ISSUE TITLE
Simulation has finished message is misspelled.

### ISSUE THREAD

**Issue by ericstephan** [GRIDAPPSD/GOSS-GridAPPS-D#1155]
### Description of Issue

Start Gridapps-d 
Run simulation
When simulation is finished the status messaged is misspelled.

Simulation # has finsihed

**Comment by nhuyvan** [comment]
I don't think I can fix this, the log messages are displayed verbatim as they are coming from the platform

**Comment by poorva1209** [comment]
I will take care of this.
