### ISSUE TITLE
Viz reporting voltage instead of power for elements.

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#1165]
### Description of Issue
Run the 123pv feeder and plot the power for the DG_36 on  2019-07-23 08:50:00 for 10 or minutes.
The Magnitude and Voltage plotted look like the magnitude and voltage (2470, -116) not the power which would close to  336124.08143804193 and angle at 179.99470002780416.

### Screenshots

![Screen Shot 2019-11-21 at 12.12.44 PM.png](https://images.zenhubusercontent.com/5877b6f951aa2c305771faa7/d96c462c-2ad0-4932-9c18-6d7c2cdd6a9f)

**Comment by nhuyvan** [comment]
This looks like a really outdated version of the Viz, I think this issue was related to this issue https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/1157 which was fixed already.

**Comment by Jeffrey-Simpson** [comment]
Okay I was work on v2019.10.0. I will test again on develop.
