### ISSUE TITLE
how to add state estimator service into gridapps-docker

### ISSUE THREAD

**Issue by updADMS** [GRIDAPPSD/GOSS-GridAPPS-D#1194]
### Description of Issue

Good day! 
We would like to ask about adding the state estimator service into gridapps-docker. We tried following the instructions from this link: https://github.com/GRIDAPPSD/gridappsd-state-estimator/blob/master/README.md
However, it seems that the SE service still does not appear among the services of the gridapps platform. Are there any other way to troubleshoot/solve this issue? 

Thank you!

**Comment by poorva1209** [comment]
@updADMS We need little more information to debug this issue. 
1. Do you see state-estimator service folder in GridAPPS-D docker under /gridappsd/services?
2. Where are you checking for state estimator service to see if it available with platform? 
3. What version of GridAPPS-D are you working with?

**Comment by updADMS** [comment]
Good day!

1. no, we cannot find it under /gridappsd-docker/gridappsd/services. 
![Screenshot from 2020-01-21 10-16-36](https://user-images.githubusercontent.com/59993065/72769911-4d8a5280-3c37-11ea-97ea-e249b1b66964.png)

2. we are actually not sure where to look. we tried checking in the gridappsd platform itself under "Applications and Services" tab of Gridappsd platform.

![Screenshot from 2020-01-21 10-20-01](https://user-images.githubusercontent.com/59993065/72770119-e28d4b80-3c37-11ea-8393-00c34cf68a9b.png)


3. we're working with v2019.12.0

------

other notes:
also, we're encountering the following errors
1. "2020-01-21 02:19:17,396 Thread-39 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1579573157374|gov.pnnl.goss.gridappsd.app.AppManagerImpl|ERROR|system|ERROR
Error while reading app config file: Is a directory" after running ./run-docker.sh

![Screenshot from 2020-01-21 10-22-35](https://user-images.githubusercontent.com/59993065/72770147-f3d65800-3c37-11ea-8404-a394603d11d0.png)

2. following the instructions from this link: https://github.com/GRIDAPPSD/gridappsd-state-estimator/blob/master/README.md
we are encountering an error after running this code: 

"sudo make LAPACK=-llapack BLAS=-lblas"

![Screenshot from 2020-01-21 10-27-19](https://user-images.githubusercontent.com/59993065/72770361-a0b0d500-3c38-11ea-9d63-a16ba7032f7a.png)

Thank you!

**Comment by updADMS** [comment]
Update on state-estimator:
the state-estimator is already reflected on the "applications and services" tab of the platform
![Screenshot from 2020-01-24 12-49-00](https://user-images.githubusercontent.com/59993065/73045283-3736fd80-3ea8-11ea-9676-8c26cee53e8d.png)

I simply added this line in the docker-compose.yml 
      - ~/git/gridappsd-state-estimator/state-estimator:/gridappsd/services/state-estimator
      - ~/git/gridappsd-state-estimator/state-estimator/state-estimator.config:/gridappsd/services/state-estimator.config
![Screenshot from 2020-01-24 12-52-52](https://user-images.githubusercontent.com/59993065/73045349-7c5b2f80-3ea8-11ea-9bce-f587235bd381.png)

Concerns:
1. I assume that since the state-estimator is already reflected on the platform as shown in the first image I will be able to use it already **but I am not sure how?** 

2. I believe it is not yet integrated with ./run-docker.sh? (based on https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/598), **so can the users still run it? how?**

3.) I also found that state-estimator also utilizes state-plotter (based on state-estimator's ./run-all.sh file), **are there special instructions so that state-estimator can properly use it?** or i just have to clone it inside ~/git along with gridappsd-state-estimator and gridappsd-sample-app

Thank you

**Comment by poorva1209** [comment]
@updADMS The containerization of the state-estimator is still in progress and is currently in the integration testing phase. We will add a comment on this task as soon as we have an update on the effort. 

May I ask what organization you are related to? What are your expectations with the state-estimator? What are your plans to use it? Thanks.
