### ISSUE TITLE
Debug Viz app on Firefox

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1195]
- [ ] simulation play button not visible/clicka-ble
- [ ] cache is not cleared while logging back in after log out.

**Comment by nhuyvan** [comment]
@poorva1209 Do you have the latest changes for Viz? The first one should have been fixed. The second one, I am not sure what happened, I am not experiencing it on my end.

**Comment by nhuyvan** [comment]
This is fixed in this merged PR https://github.com/GRIDAPPSD/gridappsd-viz/pull/281
