### ISSUE TITLE
Show power flow direction on Viz

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1202]
More discussion is needed on this.
- May make the lines thicker or add an arrow
- Viz get power flow of the line with from and to with angle -90-+90 draw arrow from from to to 
- if ~-180 from to to from
- put it on lines and switches in the middle
- for transform put it on from side
 - have the power flow option on/off (for only switches, line etc....)
- by default : off
-

**Comment by shpoudel** [comment]
I checked this feature. The feature looks really cool. Thanks, viz team. Few comments and questions:

1. In this feature, I don't think we need to display an arrow inside open switches. The switch should be visible when its status changes from open to close. 
2. Is this a static feature or a dynamic feature? I guess it is static for now. It should be dynamic because some of the apps (such as FLISR) changes the direction of power flow and it would be great to see the effect in viz. 
3. I saw the line thickness in the 9500-node model. Seems like something is off. 

I am open to chat about this issue if you have any questions.

**Comment by nhuyvan** [comment]
@shpoudel The arrows should change direction according to measurement angles, if the angles are between -90 and 90, the arrows point from left to right as you have noticed, the arrows point from right to left if the angles are close to -180

**Comment by shpoudel** [comment]
Are you looking for angles with VA for that line? What does left and right mean here?

**Comment by nhuyvan** [comment]
Currently, there's no differentiation between angles with VA or without VA, we can definitely change that. Sorry for the confusion about left and right, but you can see the arrow on this transformer changing its direction by watching this recording that I made https://imgur.com/a/3hqva4O

**Comment by shpoudel** [comment]
I saw the video but not sure what is causing that arrow to change the direction. I still didn't understand the logic you are using for the arrow.

**Comment by nhuyvan** [comment]
Can you take a look at this method which adds the arrows to the lines? https://github.com/GRIDAPPSD/gridappsd-viz/blob/develop/frontend/src/app/simulation/topology-renderer/TopologyRenderer.tsx#L198

**Comment by shpoudel** [comment]
@nhuyvan : Do you have time for a quick chat?

**Comment by AAndersn** [comment]
@nhuyvan , I have reviewed the direction indicators on the 9500 node model and have some comments. For the most part, they look amazing, but there are some issues that we need to correct.

First, looking at the laterals, this looks amazing! All of the power flow directions are correct, on both the lines and the switches. (looking at ln0138609_sw and ln0712477_sw in the bottom central portion of the feeder)

![image](https://user-images.githubusercontent.com/19935503/96498909-8a549b80-1201-11eb-9db1-82358438cc72.png)

However, the power flow on the main trunk are backwards. I have some guesses that it may be a negative powerflow value, but would need to confirm with Frank or someone more familiar with GridLab-D sign conventions. (looking at switch x8223_48332_sw next to the ones discussed above)

![image](https://user-images.githubusercontent.com/19935503/96499564-7198b580-1202-11eb-96be-91e8f81096ee.png)

Similar problem near substation S3 in far left of feeder. The powerflow indicators are backwards:

![image](https://user-images.githubusercontent.com/19935503/96500156-4cf10d80-1203-11eb-9652-a7a2f860a353.png)

There are some new problems with the stripchart plots, but I'll cover it in a different issue

**Comment by nhuyvan** [comment]
@AAndersn I'll inspect the measurements and check if they are consistent with my logic of showing the normal/reverse indicators

**Comment by AAndersn** [comment]
Some issues resolved, but not all in latest ~develop 

Line flows are mostly in the correct direction. Output from DERs is not.

Picture below shows ln1047pvfrm-1 (circled in blue, correct direction) and ln5000CHP-1 (circled in red, incorrect direction)

![image](https://user-images.githubusercontent.com/19935503/107589720-7ae7cc80-6bbb-11eb-97b1-65fb4c9d71f8.png)

**Comment by nhuyvan** [comment]
Thank you @AAndersn for the detailed reporting, it's honestly very helpful, I'll get to fixing it soon

**Comment by AAndersn** [comment]
@nhuyvan , trying to be helpful wherever I can. If there is anything else I can support you with for this task, just let me know :)

**Comment by bibiraju** [comment]
@AAndersn I just merged the PR 'Change directions of lines and switch' #380 into develop. Please test and let us know if there are more issues. The fix is already in develop.

**Comment by AAndersn** [comment]
@nhuyvan @bibiraju I think we are 90% there. Running the 9500 node model, it looks perfect except one line that is still backwards.

Here are ln1047pvfrm-1 and ln5000CHP-1 that we used last time. They look exactly right:

![image](https://user-images.githubusercontent.com/19935503/110551868-32a0c900-80eb-11eb-8fac-6a75f3b831c2.png)

So does the rest of the area, except LN5833611-1 and heading up from there. The power flow direction should be up not down:

![image](https://user-images.githubusercontent.com/19935503/110552738-b5765380-80ec-11eb-9119-ba2aeddfc14d.png)

**Comment by nhuyvan** [comment]
@AAndersn Thank you very much for such a detailed, high quality reporting, it will definitely help me out a lot

**Comment by AAndersn** [comment]
@nhuyvan , I checked it in detail and the arrows are all correct for the base case

However, they are not updating / changing when I open and close switches to reconfigure the feeder. Should I open a new issue for that or keep it in this one?

**Comment by nhuyvan** [comment]
@AAndersn Can you open/close different types of nodes or switches at different locations to see if the line arrows change direction?

**Comment by AAndersn** [comment]
@nhuyvan , here are the screenshots showing the line direction staying the same when switches are opened and closed. I am thinking about closing the current issue and starting a new issue related to this.

Basecase at start of simulation is correct:
![image](https://user-images.githubusercontent.com/19935503/113608920-02701b80-9600-11eb-9a64-4268bf72ee1f.png)

After switching actions, arrows stay the same. [open tsw30473047_sw and close ln0653457_sw]
![image](https://user-images.githubusercontent.com/19935503/113609148-3fd4a900-9600-11eb-842c-5334c6d2b474.png)
