### ISSUE TITLE
Add Plots for min, max , avg voltages and load demand in Viz

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1204]
need to know more bout load demand ?

**Comment by bibiraju** [comment]
@poorva1209 @temcdrm Could you elaborate on this? Is the idea to add default plots on Viz for min, max, avg voltages and load demand?

**Comment by temcdrm** [comment]
- One graph would plot the min of all measured voltages, the max of all measured voltages and the average of all measured voltages. Convert the voltages to percentage of nominal first.
- The second graph would plot the sum of all measured EnergyConsumer p, the sum of all EnergyConsumer q, the sum of all solar p, the sum of all solar q (often zero), the sum of all battery p, and the sum of all battery q (often zero). Convert to kw and kvar first, but the vertical axis label could just say "kva" if you plot all six on the same graph.

**Comment by bibiraju** [comment]
@temcdrm How do we get the nominal voltage? Is it this query? Or can we find it in feeder_limits.json?
# list all the connectivity node base voltages by feeder, for visualization
PREFIX r:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX c:  <http://iec.ch/TC57/CIM100#>
SELECT DISTINCT ?feeder ?busname ?nomv WHERE {
# VALUES ?fdrid {"_49AD8E07-3BF9-A4E2-CB8F-C3722F837B62"}  # 13 bus
 ?fdr c:IdentifiedObject.mRID ?fdrid.
 ?bus c:ConnectivityNode.ConnectivityNodeContainer ?fdr.
 ?bus r:type c:ConnectivityNode.
 ?bus c:IdentifiedObject.name ?busname.
 ?fdr c:IdentifiedObject.name ?feeder.
 ?trm c:Terminal.ConnectivityNode ?bus.
 ?trm c:Terminal.ConductingEquipment ?ce.
 ?ce  c:ConductingEquipment.BaseVoltage ?bv.
 ?bv  c:BaseVoltage.nominalVoltage ?nomv.
}
ORDER by ?feeder ?busname ?nomv

**Comment by temcdrm** [comment]
yes, that query should get you the nominal voltage for every ConnectivityNode.  It might also be in the feeder limits JSON, i.e., the average of Alo and Ahi for each ConnectivityNode.

**Comment by bibiraju** [comment]
> * The second graph would plot the sum of all measured EnergyConsumer p, the sum of all EnergyConsumer q, the sum of all solar p, the sum of all solar q (often zero), the sum of all battery p, and the sum of all battery q (often zero). Convert to kw and kvar first, but the vertical axis label could just say "kva" if you plot all six on the same graph.

@temcdrm How do we get the p and q for energy consumer, solar and battery?

**Comment by temcdrm** [comment]
In the **rootname_dict.json** file, Measurements section, you should find p and q measurements for each of those.  The idea was to sum all p measurements for EnergyConsumer, sum all p measurements for batteries, etc.

**Comment by temcdrm** [comment]
I'm attaching a sample dictionary file.  For batteries and solar panels, the naming scheme of relevant measurements will be **PowerElectronicsConnection_BatteryUnit_** and **PowerElectronicsConnection_PhotovoltaicUnit_**, respectively.  The quantities of interest are **VA** on each phase.  These will be complex numbers, of which **p** and **q** are the real and imaginary parts, respectively.
[ieee13_dict_json.txt](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/5132783/ieee13_dict_json.txt)

**Comment by bibiraju** [comment]
> In the **rootname_dict.json** file, Measurements section, you should find p and q measurements for each of those. The idea was to sum all p measurements for EnergyConsumer, sum all p measurements for batteries, etc.

I don't see p and q values in the measurements section of the model_dict.json.

**Comment by temcdrm** [comment]
p is the real part of a **VA** measurementType, and q is the imaginary part of a VA measurementType.  For example, this is a p+jq measurement on phase s1 of a battery:


{"name":"PowerElectronicsConnection_BatteryUnit_house","mRID":"_b86d8775-6dd7-4168-9dca-7cb495303977","ConductingEquipment_mRID":"_682AB7A9-4FBF-4204-BDE1-27EAB3425DA0","Terminal_mRID":"_A4B4C25C-8744-4B8B-A612-19B80AFA110D","measurementType":"**VA**","phases":"s2","MeasurementClass":"Analog","ConductingEquipment_type":"PowerElectronicsConnection","ConductingEquipment_name":"house","ConnectivityNode":"house","SimObject":"house_stmtr"}

**Comment by temcdrm** [comment]
If the VA measurement value comes to the GOSS bus as a complex number in Cartesian coordinates, then the you take p as the real part and q as the imaginary part directly.  If the values come in polar coordinates, then p=Magnitude * cos (Angle) and q = Magnitude * sin (Angle), where the Angle is probably in degrees.
