### ISSUE TITLE
Alarm changes

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1207]
- [ ] Change alarm values as open/close 
- [x] Show node position when clicking on alarm

**Comment by nhuyvan** [comment]
Second one was done in this commit https://github.com/GRIDAPPSD/gridappsd-viz/commit/3c3e0019164a273bc64673288bfa1897a7af3267

**Comment by nhuyvan** [comment]
@poorva1209 For the first item, 1 is open and 0 is closed, isn't it?

**Comment by poorva1209** [comment]
> @poorva1209 For the first item, 1 is open and 0 is closed, isn't it?

I will send Open/close instead of 0/1 from alarm service, so you don't have to convert them, just display as it is.
