### ISSUE TITLE
Viz plot changes

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1208]
- [x] add units. use whole numbers where needed. 
- [x] go to node when clicking on plot.
- [x] label overlapping plot lines

**Comment by nhuyvan** [comment]
labels for the overlapping lines

<img width="1440" alt="Screen Shot 2020-02-07 at 8 45 42 PM" src="https://user-images.githubusercontent.com/13056129/74079339-d56bad00-49ea-11ea-911e-6fbef8b576f8.png">

**Comment by nhuyvan** [comment]
The second item is implemented in this PR https://github.com/GRIDAPPSD/gridappsd-viz/pull/286

![Screen Recording 2020-02-10 at 3 06 29 PM 2020-02-10 15_10_39](https://user-images.githubusercontent.com/13056129/74198921-8c4c7080-4c17-11ea-9234-c2f70741c595.gif)

**Comment by nhuyvan** [comment]
The second part of the first item was implemented in this commit https://github.com/GRIDAPPSD/gridappsd-viz/commit/66e4ed7757921bf71aac7106ed0eebf30312b166

**Comment by nhuyvan** [comment]
The first part of the first item was implemented in this PR https://github.com/GRIDAPPSD/gridappsd-viz/pull/295
