### ISSUE TITLE
Timestamp for voltage violation and alarms should be simulation time not current time

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1252]
I will update voltage violation and alarm service to publish timestamp along with output.
Display that timestamp instead of the current time.

**Comment by nhuyvan** [comment]
Since this was a really tiny change, I merged the fix for it myself, so I'm closing this

**Comment by ericstephan** [comment]
I need to double check how alarms are stored in Proven.
