### ISSUE TITLE
Enable the Upload and Selection of New "Player Files" for Load Fluctuations

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#1263]
### Description of Issue
During simulation, GridLAB-D always varies the circuit loads with time according to this default profile: https://github.com/GRIDAPPSD/gridappsd-data/tree/master/timeseries/loadprofiles. A GridLAB-D model is exported from Blazegraph with _-n=ieeezipload_ option to invoke this behavior. Users need the ability to change this behavior by uploading their own "Player Files".

Steps to resolve the issue may break down like this:

- Store the player files in Proven, rather than a single hard-wired location.
- Provide a way for users to upload one or more player files. These would be in CSV format, with uniform or non-uniform time steps. If a uniform time step, the column for time stamps is often omitted in the source data. One or two columns may be provided for scaling the real and reactive power uniformly, or separately. Separate columns (or column pairs) may be provided for total power, or individual phases. During upload, the data should be normalized to the peak value so it becomes a profile of scaling factors.
- The platform GUI should provide a way for the user to select one of the stored player files from Proven. 

At present, one player file must apply to all loads in the circuit. Eventually, we will probably have to support separate player files for different load, different DER, or various groupings of those component. Consideration may be given to generalizing the design to facilitate those extensions later on, but they don't have to implemented now.

### Expected Timeline
Avista/OES would like to have a trial version of this feature by the end of April. If necessary, we could mock this up by substituting one of their profiles for our default profile, in a hard-wired fashion.

### Additional Details
Avista/OES have provided their own sample profiles here: https://stash.pnnl.gov/projects/GRIDADDEV/repos/oesdemo/browse/historian_data
Those profiles are based on actual measurements. The profiles are in a private repository, but Avista has given permission to make those profiles publicly available as part of the platform after these proposed features have been implemented. These profiles can be used as realistic scaling factors, without the Avista feeder models in the private repository, which remain confidential.

**Comment by ericstephan** [comment]
Here are my recommendations:

- Partitioning -

- To support loadprofiles being uploaded a separate “loadprofile” Influx database could be created as opposed to putting everything in proven’s default database. 

- A second option creating all load profile measurements as a separate measurement prefixed with the name “loadprofile” for example: “loadprofile.loadprofile1”. 

- Due to the nature of the time-series data (10-second intervals) my preference is to start each user profile time with the Epoch midnight January 1, 1970 (0 time).

With a few minor alterations, the loadprofile_measurement_bulk.py script could be used to manage the bulk loading for users.

**Comment by ericstephan** [comment]
I've created a new script and tested it out loading one of the demo profile files.  I'll wait for feedback from you on how to proceed.  @temcdrm @ericstephan

**Comment by ericstephan** [comment]
@poorva1209 @temcdrm in terms of a gui supporting user created low-profile, I really believe we should leverage the blazegraph database to catalog the profiles.  @telsethag @bibiraju or I can help with that if you'd like.
