### ISSUE TITLE
Condition of Inverted Matrix is too High for Reliable Numeric Inversion

### ISSUE THREAD

**Issue by areiman** [GRIDAPPSD/GOSS-GridAPPS-D#1265]
Follow-up on the investigation of the Ybus matrix, the estimated condition of the matrix to be inverted is several orders of magnitude higher than that of the Ybus. For the 9500 node model, the condition is much too for numerically reliable inversion.

**Comment by garydblack** [comment]
KLU condest values for conditional values for Supd that is input to the KLU factor() method:

13 node, no capping: 4.94846e+18, 2.9529e+18, 2.9513e+18
13 node, with capping: 1.41062e+17, 8.67516e+16, 8.62634e+16

123 node, no capping: 5.11593e+18, 2.98839e+18, 3.00054e+18
123 node, with capping: 2.6321e+16, 1.84938e+16, 1.75708e+16

9500 node, no capping: 2.06571e+25, 4.00267e+26
9500 node, with capping: 7.14165e+22, 7.67386e+24
9500 node, with capping: 7.14165e+22, 3.81865e+24, 1.00898e+24, 1.15887e+25, 3.10954e+25, 1.25456e+24, 7.91168e+23, 6.08328e+22
