### ISSUE TITLE
Create a utility program that combines cdpsm profiles

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1277]

**Comment by temcdrm** [comment]
The attached ZIP file contains the IEEE13-bus models in two formats, one with asset catalog and one without.  The one without also has two PV and two batteries. The utility program should be able to merge 6 subprofiles into a combined XML, which would be similar to the combined model export.  See attachment for issue #1276 on how the exports are done.

The draft sub-profile UML diagrams are also attached.
[CDPSM2_1.pdf](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/4611796/CDPSM2_1.pdf)

[test_xml.zip](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/4611782/test_xml.zip)

**Comment by ericstephan** [comment]
Nice Tom!

Eric
________________________________

**Comment by temcdrm** [comment]
Here are two more samples, in which transmission system models have been broken down into about 4 common power system model (CPSM) sub-profiles. The XML combiner utility should be flexible enough to handle these, along with any subsequent modifications to the CPSM and/or CDPSM profiles.  Both profiles are subject to revision as we approach the interop tests. 
[ABB40Bus.zip](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/4611986/ABB40Bus.zip)
[savnw_nb_CIM16.zip](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/4611987/savnw_nb_CIM16.zip)

We can assume the EQ profile is the main one for CPSM, and build on that for transmission system models.  We can assume the FUN profile is the main one for CDPSM, and build on that for distribution system models.

Note: we are going to use GridLAB-D and OpenDSS to solve the CDPSM models. We are going to use GridPACK to solve the CPSM models - it's a Ubuntu install from here: https://www.gridpack.org/wiki/index.php/Ubuntu_Installation
