### ISSUE TITLE
Change Load Reactive Power through Platform Messages

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#1286]
In fncs_goss_bridge.py, the message to change EnergyConsumer.p is implemented with a change to the GridLAB-D base_power attribute, which is apparent power [VA]. Changing this attribute changes both real and reactive power, although when using the original IEEE zipload player file, the power factor is held constant. Some applications need to control reactive power separately. There are two aspects of this issue:

1. EnergyConsumer.p should change only the real power, even when using a player file. If the reactive power is left unaffected, we can assume constant power factor for backward compatibility.

2. A new EnergyConsumer.q should change only the reactive power, even when using a player file.

**Comment by afisher1** [comment]
Apps have the capability to change P and Q now for a long time. Closing this issue.
