### ISSUE TITLE
Create a query to delete a feeder model from blazegraph

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1304]

**Comment by temcdrm** [comment]
Implemented in the Python script here: https://github.com/GRIDAPPSD/CIMHub/blob/develop/utils/DropCircuit.py

The 12-step test script is here: https://github.com/GRIDAPPSD/CIMHub/blob/develop/utils/drop_test.sh

In summary, the test script loads two versions of the IEEE 13-bus feeder, inserting measurements and houses, from a sibling Powergrid-Models directory. Then, it attempts to create and solve the models in OpenDSS and GridLAB-D, following different sequences of deleting one feeder or the other.  Each time the script pauses, please scroll up to review the diagnostic outputs, especially the csv listings from successful (or failed) OpenDSS and GridLAB-D simulations.  The expected results are:

- Model created and solved if the data is still in Blazegraph, but it fails if and only if that circuit was deleted.
- At the end of the test, there are 2 instances (6 tuples) of the CIM version, and then those are deleted as well.

At the end of the test sequence, Blazegraph DB will be empty.

There are snippets of the deletion queries near the top of this file: https://github.com/GRIDAPPSD/CIMHub/blob/develop/queries.txt that could be used in the browser, but note that the order of execution is important.  See the DropCircuit.py file for an example of correct sequencing.
