### ISSUE TITLE
Provide a way to set the seed in the fncs_goss_bridge.py so that the test results are consistent.

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#1312]
### Description of Issue
Comparison of the values from the pv inverters are difficult since the angle measurement is inconsistent. They can be randomly 0,180 or -180. So a way to set the seed in the fncs_goss_bridge.py would keep test results are consistent.

**Comment by afisher1** [comment]
This is not an issue any longer. Closing
