### ISSUE TITLE
Create unit tests for token based auth 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1325]

**Comment by craig8** [comment]
@tdtalbot I think that we should just use the integration tests inside gridappsd-python for these and then do some negative testing there.

In develop now there is two functions for the generic login case that needs to work in order for any of these tests to pass.

https://github.com/GRIDAPPSD/gridappsd-python/blob/d02b52e14127100a370c6d06e6d3588042e3d50f/tests/conftest.py#L17 and
https://github.com/GRIDAPPSD/gridappsd-python/blob/d02b52e14127100a370c6d06e6d3588042e3d50f/tests/conftest.py#L29

We could add an invalid password on the client side when failure happens (maybe you have done this).  Anyways, that's the easy way to get these tested at least against the platform without having to mock everything up.

I could imagine having a function that creates more gridappsd objects with different username/password combos and such.
