### ISSUE TITLE
Work on system wide time synchronization and conversion

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1329]
- weather data timezone MNT- to UTC conversion (sunrise doesn't make sense)
- gridappsd time which makes to solar time 
- browser doing local conversion  (use solar forecast app and viz to test, changes in testing in a different timezone )

**Comment by Jeffrey-Simpson** [comment]
The VIZ  should have a setting for timezone so it is clear what time is used and what the time will be when it is converted to UTC and sent with the simulation request. The timezone should also be add to the date string used in the events file.

For example the current Viz just uses the current time zone:
Set time to 12-01-2020 00:00:00 in the Viz

Get :
gridappsd@31e628e15b55:/tmp/gridappsd_tmp/246305156$ more model_startup.glm 
clock {
     timezone "UTC0";
     starttime '2020-12-01 07:00:00';
     stoptime '2020-12-01 07:02:00';
}


##
goss.gridappsd.process.request.data.timeseries
 
{"queryMeasurement": "simulation",
"queryFilter": {"simulation_id": "246305156", "hasSimulationMessageType": "OUTPUT"},
"responseFormat": "JSON"}

Returns

[
    {
        "hasSimulationMessageType": "OUTPUT",
        "measurement_mrid": "_0018886d-363a-456c-8b1b-116e8c2e6fc6",
        "angle": -86.14616127814321,
        "magnitude": 1.621256060956751,
        "simulation_id": "246305156",
        "time": 1606806002
    },
    {
        "hasSimulationMessageType": "OUTPUT",
        "measurement_mrid": "_fff7495d-7f99-4092-a1d7-ecbbf7df76e1",
        "angle": 25.460179697818603,
        "magnitude": 45275.364772485984,
        "simulation_id": "246305156",
        "time": 1606806002
    },

**Comment by bibiraju** [comment]
Created Issue on Viz to add timezone  #1426
