### ISSUE TITLE
Measure battery state of charge (SoC)

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#1347]
1. Add "SoC" as a measurement type for InsertMeasurement.py and supporting scripts
2. Add "SoC" to the measurements in model dictionary
3. Support "SoC" in the bridge

**Comment by temcdrm** [comment]
The appropriate model dictionary entry names will start with **PowerElectronicsConnection_BatteryUnit**. They will have **SoC** for measurementType and **none** for phases. The SimObject will refer to the battery instead of the inverter's parent meter.  Here is an example of SoC measurement for a battery:

{"name":"PowerElectronicsConnection_BatteryUnit_school","mRID":"_4d12d2be-3f2f-4c5a-b151-159222562522","ConductingEquipment_mRID":"_7B671984-4C56-4FF1-9733-B4B6FCA5F2AA","Terminal_mRID":"_90D2243E-05D4-432C-A23B-A6B8D732B027","measurementType":"**SoC**","phases":"**none**","MeasurementClass":"Analog","ConductingEquipment_type":"PowerElectronicsConnection","ConductingEquipment_name":"school","ConnectivityNode":"634","SimObject":"**bat_school**"},

Here is an example of the phase A complex power measurement on that same battery/inverter:

{"name":"PowerElectronicsConnection_BatteryUnit_school","mRID":"_96112d69-43d7-46fe-b29f-aff73ed1debf","ConductingEquipment_mRID":"_7B671984-4C56-4FF1-9733-B4B6FCA5F2AA","Terminal_mRID":"_90D2243E-05D4-432C-A23B-A6B8D732B027","measurementType":"**VA**","phases":"**A**","MeasurementClass":"Analog","ConductingEquipment_type":"PowerElectronicsConnection","ConductingEquipment_name":"school","ConnectivityNode":"634","SimObject":"**634_stmtr**"},

Parts 1 and 2 of the initial comment have been fixed on the issue/1347 branch. Creating a new issue for part 3.

**Comment by singha42** [comment]
For Avista model, its not present. The measurement type of BatteryUnit is "VA" or "PNV"

**Comment by temcdrm** [comment]
This is not a platform issue.  Somebody just needs to run the updated measurement script against the Avista model.
