### ISSUE TITLE
Estimation of ZIP parameters for the house load. 

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1350]
I do have a couple of questions on this task:

1. Where can I find the details of house model used in 9500-node model? Also, the player file for load multiplier. I understand these data are not meant to be available for app developers. I need these to get started with.
2. Can you please point me to the script that is used to populate the model with houses?

**Comment by temcdrm** [comment]
https://github.com/GRIDAPPSD/Powergrid-Models/tree/develop/houses
