### ISSUE TITLE
Offline Simulation+App Launcher

### ISSUE THREAD

**Issue by areiman** [GRIDAPPSD/GOSS-GridAPPS-D#1364]
Build a simulation request, launch a simulation, get the simulation ID, pass request (which includes the feeder mRID) and simulation ID to an app; avoids using the Viz and/or copying files into platform containers to launch apps; primarily for debugging and demonstration purposes.

**Comment by garydblack** [comment]
In MV there is now a sim_starter.py that in combination with the run-navigator.sh wrapper script will start a simulation if desired and pass the SIMID and SIMREQ to the MV main supervisor.

To utilize this from state-estimator, the cleanest way is to create a gridappsd-sim-starter github repo and then reference this module in both the SE and MV repos.  This should be a folder containing sim_starter.py along with the JSON config files now living under simulation_config files.
