### ISSUE TITLE
Plot selection page not updating when model is changed.

### ISSUE THREAD

**Issue by bibiraju** [GRIDAPPSD/GOSS-GridAPPS-D#1375]
Need to try reproducing the issue

**Comment by bibiraju** [comment]
@poorva1209 I couldn't reproduce the issue. Please let me know the steps to reproduce the issue

**Comment by poorva1209** [comment]
@bibiraju Can I call you Team right now?

**Comment by poorva1209** [comment]
@bibiraju I tried again even I can't reproduce it :) 
I will try again and let you know when I can.

**Comment by bibiraju** [comment]
@poorva1209 I tried again but could not reproduce the issue.

**Comment by poorva1209** [comment]
Resolved. Closing the issue.
