### ISSUE TITLE
Add current time to all Proven measurements 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1378]

**Comment by ericstephan** [comment]
This has been added and a new release providing this option has been released as v1.3.7.2 off of the proven=cluster Master branch

**Comment by ericstephan** [comment]
@tonya1 Can you make a new proven-cluster docker container for @poorva1209 to test?  The new master branch release number is v1.3.7.2.

**Comment by tonya1** [comment]
@ericstephan Created gridappsd/proven:1.3.7.2
