### ISSUE TITLE
Unable to select simulation IDs for the Select Comparison Type on the Viz

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#1386]
### Description of Issue
After running simulations I am select simulation IDs for the Select Comparison Type on the Viz.

### Affected Version
Current develop branch.

**Comment by nhuyvan** [comment]
This is caused by the platform returning an empty list of simulation IDs, I already asked Poorva to take a look at why that is happening
