### ISSUE TITLE
Reduce build time for State estimator - SuiteSparse 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1391]
- Use the subset of SuiteSparse 
- Anything else we can do to reduce the build time.

**Comment by craig8** [comment]
@tonya1 now that we are using workflows we should be able to archive the build and just extract them from the archive...at least that's a thought.  We wouldn't get updates from SuiteSparse but it would be faster...

**Comment by tonya1** [comment]
The build process has been moved to the base build for now.  This should help out the folks building goss-gridapps-d locally.  Will look into artifacts and sharing across repo builds.  That would be ideal.

**Comment by tonya1** [comment]
doesn't look promising.  From https://docs.github.com/en/free-pro-team@latest/actions/guides/storing-workflow-data-as-artifacts

You can only download artifacts that were uploaded during the same workflow run

We could possibly look into our own artifact storage on AWS S3.  I will close this item for now.  If we decide we want to pursue artifact storage we can open a new task.
