### ISSUE TITLE
Add Support Influx Native Query Through Time Series Data Manager

### ISSUE THREAD

**Issue by ericstephan** [GRIDAPPSD/GOSS-GridAPPS-D#1394]
### Description of Issue

The original intent of the Time Series Data Manager was to provide a platform-independent GridAPPS-D query interface to the underlying Influx.  For more complex queries an API needs to be provided to pass a native influx query through the GridAPPS-D API.

**Comment by ericstephan** [comment]
@poorva1209 the following reserved characters (below) require a backslash in a JSON string.  I think I'll only need the double quote to move a native query through the time series data manager.  Is this your understanding from a JSON perspective?

Backspace is replaced with \b.
Form feed is replaced with \f.
Newline is replaced with \n.
Carriage return is replaced with \r.
Tab is replaced with \t.
Double quote is replaced with \"
Backslash is replaced with \\

**Comment by poorva1209** [comment]
@ericstephan Yeah, that is right. If you can paste an example here then I can confirm here too.

**Comment by poorva1209** [comment]
Not needed anymore due to generic timeseries API.
