### ISSUE TITLE
Incorrect CIM import and export for some line segments

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1410]
This post is to report the issues related to CIM export and import as identified by the Model Validation application. 

**Issue 1**
Some of the OpenDSS line segments have impedance directly specified without reference to a linecode or geometry. Their units get zapped and the CIM is not exported correctly. We identify this issue in the following line segment:

New Line.645646    Phases=2 Bus1=645.3.2      Bus2=646.3.2    Length=0.0568  units=mi normamps=230
~ rmatrix = (1.3238 | 0.2066 1.3294 ) 
~ xmatrix = (1.3569 | 0.4591 1.3471 ) 

In this case, the rmatrix and xmatrix are changed into ohm/m during CIM export, and length is exported as m which is expected. However, the length is exported irrespective of the original unit and the value is CIM is 0.0568m. 

**Issue 2**
On the other hand, there is a similar issue when the exported CIM is converted back to OpenDSS. This belongs to those lines that are defined with the individual ACLineSegment attributes. The impedances (r, x, r0, x0) are directly used as it is from CIM XML while the length is converted to ft. 

Original OpenDSS:
New Line.HVMV_Sub_connector  bus1=HVMV11sub1_LSB      bus2=HVMV_Sub1_48332     length=0.001       units=km r1=0.001 r0=0.001 x1=0.01 x0=0.01 c1=0 c0=0

CIM to OpenDSS: 
new Line.hvmv_sub_connector phases=3 bus1=hvmv11sub1_lsb.1.2.3 bus2=hvmv_sub1_48332.1.2.3 length=3.3 units=ft
~ normamps=400.00 emergamps=600.00
~ r1=0.000001 x1=0.000010 c1=0.000000 r0=0.000001 x0=0.000010 c0=0.000000

@temcdrm - I think the second issue is a quick fix on **DistLinesInstanceZ**. 

@areiman @poorva1209

**Comment by temcdrm** [comment]
fixed issue 1 in build 1.2.15 of OpenDSSCmd
fixed issue 2 in the issue/1175 branches off Powergrid-Models and CIMHub

**Comment by temcdrm** [comment]
There is a pull request from opendss/v1.2.15 to develop on GOSS-GridAPPS-D

**Comment by shpoudel** [comment]
Resolved issue 1 by updating the XML file for the IEEE 13Node Assets model.
