### ISSUE TITLE
Different Unit Conversion in OpenDSS and CIM importer

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1411]
Recently, we noticed there is some inconsistency during the unit conversion (length of the line segment). This was identified when the model validation application was computing the admittance matrix using CIM XML data and comparing it against the platform Ybus export which comes internally from base OpenDSS. 

![image](https://user-images.githubusercontent.com/35777492/104051333-d4b03d80-519c-11eb-949d-962a9c1e0b4c.png)

These small differences in unit conversion get reflected in the computed Ybus and were captured during the model validation process.

@areiman @temcdrm

**Comment by temcdrm** [comment]
changed 1609.344 to 1609.3, and 3.2809 to 1.0/0.3048 in the issue/1175 branches of Powergrid-Models and CIMHub

**Comment by temcdrm** [comment]
opendsscmd v1.4 will have 1609.344, and greater precision of pi. Fixed in https://github.com/GRIDAPPSD/CIMHub/commit/31199b4c223e570e7388124fccea57f96cb219f6
