### ISSUE TITLE
Unexpected lower voltages at some node with houses = true in timeseries simulation

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1412]
I was running an offline simulation for two weeks to get the training data by pulling the base GridLAB-D file and weather file. While checking the status of the simulation, I noticed several warnings related to a lower voltage (outside of ANSI standards).  I picked one particular meter data  (ld_323235b0_ldmtr)  for 10 mins to show this issue. The power and voltage plot suggests that the lower voltage is because of very high demand during that time. The plot is generated from 2013-07-06 11:50:00 UTC to 2013-07-06 12:00:00 UTC. 

![image](https://user-images.githubusercontent.com/35777492/104053291-cfa0bd80-519f-11eb-9e62-b35f894cd7ae.png)

I am not sure why the demand for some houses increases so drastically (much higher than the nominal load) for some time steps that cause the voltage to drop significantly. I am also attaching the zip file with 4 CSV files that records the voltage and power at all 1275 load nodes every 15 seconds. 

[Nodal_PandV.zip](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/5788919/Nodal_PandV.zip)

**Comment by shpoudel** [comment]
The entire two weeks' data was ready and I plotted the power and voltage at one of the load meters randomly picked out of 1275 from the 9500-node model. It seems like there is something off. Some parameters (weather or house model itself) are causing the demand to increase unexpectedly at some intervals. 

![image](https://user-images.githubusercontent.com/35777492/104392081-31418e80-54f6-11eb-9a1f-4576473e3ba6.png)

**Comment by shpoudel** [comment]
Following from the last discussion:
1. The feeder demand sometimes goes to ~12 MW during the time series simulation.
2. The triplex line has a very little drop,  and I don't think it is the main cause of the above mentioned under voltage.

Originally, the feeder had a fixed amount of load connected after a transformer. Can we use that nominal load to populate the houses for a transformer? During the simulation, I observed the total loads consumed by the houses fed by a service transformer are much higher than the previously allocated nominal load even though the consumption is below the kVA rating of the transformer (Some sample results attached). 

@temcdrm Can you please suggest some solution to this? 

![image](https://user-images.githubusercontent.com/35777492/104973493-b8d14680-59a9-11eb-9b5d-1db23d2a2731.png)

**Comment by temcdrm** [comment]
This doesn't seem to happen with latest updates to [PR 106](https://github.com/GRIDAPPSD/Powergrid-Models/pull/106), which contains many updates to the transformer and load modeling. Lowest voltage in the 8500 and 9500 node models is about 0.91 per-unit, and most are higher.
