### ISSUE TITLE
CIMHub Python Script Deployment

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#1448]
The scripts in CIMHub/utils should be deployed to pypi so that ```pip3 install cimhub_utils``` can be used, instead of cloning all of CIMHub

**Comment by temcdrm** [comment]
Craig - I am working on the resolution of this issue for other labs to use in our SETO OEDI project. The proposed user installation experience would be:

- `pip3 install cimhub`
- Docker and the Blazegraph container still must be installed separately.

A sample user Python script would be:

- `import cimhub.api as cimhub`
- `cimhub.list_feeders()`
- `cimhub.summarize_db('db.cfg')`
- other functions to be implemented

The source directory structure, implemented but not pushed on `feature/cimext`, is:

- `~/src/CIMHub/setup.py`
- `~/src/CIMHub/setup.cfg`
- `~/src/CIMHub/src_python/cimhub` has the `__init__.py` and other Python source files

What do you think? I'm in the process of testing for standalone use of CIMHub. Once that works, I would rework Powergrid-Models for the platform to use this Python package.

**Comment by craig8** [comment]
yeah do you want me to add an action that will do that for you when you push a version tag

**Comment by temcdrm** [comment]
pip3 install cimhub works [CIMHub PR #27](https://github.com/GRIDAPPSD/CIMHub/pull/27)
