### ISSUE TITLE
Viz crashes when stopping, starting new simulation with HELICS

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/GOSS-GridAPPS-D#1481]
Testing ability of platform to stop and start a new simulation. 

The terminal window shows that a second simulation has started and is running, but the Viz never gets past the bouncing dots in the log window

![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/f7c34f05-60d9-4a58-8d08-4aba1313519f)

Also cntrl+C in the docker container terminal window no longer kills the platform. Instead CPU usage goes up to 97% and the docker container stops accepting any commands.

![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/99dd076d-7fa5-428f-8a91-5b3ffa90efda)

**Comment by poorva1209** [comment]
Please pull latest develop and try again.

**Comment by AAndersn** [comment]
Test 1 - allow simulation to finish and then re-start the same simulation --> **works for first simulation restart, but then cannot restart for a second time**

![image](https://user-images.githubusercontent.com/19935503/113752183-88a06680-96c1-11eb-909e-7a0893b75213.png)
![image](https://user-images.githubusercontent.com/19935503/113752253-98b84600-96c1-11eb-9f27-1676d16c71c0.png)
![image](https://user-images.githubusercontent.com/19935503/113752456-dae18780-96c1-11eb-8033-86c4845dd581.png)
![image](https://user-images.githubusercontent.com/19935503/113752674-15e3bb00-96c2-11eb-97cd-c8618fdef1cc.png)


Test 2 - Stopping ./run-gridappsd.sh with cntrl+C --> PASS

Test 3 - Stopping simulation using stop button and restarting the same simulation --> **same problem, works the first time, but fails the second time**

![image](https://user-images.githubusercontent.com/19935503/113753022-796de880-96c2-11eb-9eb2-28b4609ef1a5.png)
![image](https://user-images.githubusercontent.com/19935503/113753281-c5b92880-96c2-11eb-9d72-73e3899036be.png)
![image](https://user-images.githubusercontent.com/19935503/113753297-cbaf0980-96c2-11eb-9330-2f3e8ed37d60.png)

**Comment by poorva1209** [comment]
@AAndersn The issue you mentioned above is a different one which you reported here: #1482. That error is with HELICS and I am working on debugging and resolving it. 

This current issue is just for Viz to see if it can correctly stop and restart simulations with HELICS, which it is doing correctly. You should not see just bouncing dots as reported earlier.
