### ISSUE TITLE
The Model Validation application identified issues while validating the exported Ybus from the platform

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1483]
The following issues in CIM Importer are mostly related to the GetDSS function. 

1. The %noloadloss parameter for DistXfmrCodingRating (open circuit test) doesn't convert kW to %. The correct equation should be: " %noloadloss=" + df3.format(1000 * 100 * oct.nll / ratedS[0]). 

2. The core admittance parameters for DistPowerXfmrWinding calculates zbase using the end number (core.wdg) which is 1 and is referring to the primary winding. However, using that core.wdg in CIM Importer is taking the secondary winding while calculating zbase thus making the round trip conversion incorrect. 

3. The %noloadloss  uses core.b in the equation instead of core.g

@areiman @garydblack

**Comment by temcdrm** [comment]
fixed on CIMHub master branch
