### ISSUE TITLE
Missing measurements from Simulator Output

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1499]
When querying for a CIM dictionary for a model (IEEE 13 node assets for now), I am seeing Simobject as "null" for different equipment types. See image attached

![image](https://user-images.githubusercontent.com/35777492/112177560-4867c100-8bb6-11eb-9010-767c2264a89c.png)

Upon running the simulation, there is a warning in the gridappsd-docker terminal "All measurements for object null are missing from the simulator output".

**Comment by poorva1209** [comment]
@shpoudel  Can you confirm this and close
