### ISSUE TITLE
Load-Flow Validation

### ISSUE THREAD

**Issue by areiman** [GRIDAPPSD/GOSS-GridAPPS-D#1500]
Given a valid Ybus matrix and an error-free substation voltage measurement and a set of error-free load injection measurements, a distribution load-flow solution provides an expected substation injection and a set of expected system voltages. We will compare these expected distribution load-flow outputs to GridAPPS-D simulation outputs in order to validate the latter. Differences will occur whenever the simulated system model does not match the validated Ybus matrix.

**Comment by shpoudel** [comment]
The static Ybus matrix computation doesn't include shunt element contribution from transformers. Will need to fix this for power flow validation and dynamic Ybus service.

**Comment by garydblack** [comment]
I think we are considering this as done.
