### ISSUE TITLE
Test control commands for OCHRE model

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1519]
Test the control commands with IEEE 13 node OCHRE model once they are added to the bridge.

**Comment by shpoudel** [comment]
I tested the control commands for OCHRE as suggested by @afisher1 

![image](https://user-images.githubusercontent.com/35777492/118543493-2cd9ec00-b709-11eb-9451-471ca60d22ca.png)

It breaks with an error-- "Forward difference command cannot be parsed correctly one or more of attributes needed was None". I think this is expected as there is no house information in model_dict.json and there cannot be a CIM mapping for house object thus giving name, phases, type... as NULL. Is this the correct observation?

**Comment by afisher1** [comment]
You are correct. I've fixed this by preventing this parsing check to occur when the attribute is "Ochre.command"
