### ISSUE TITLE
Only one input command coming back from timerseries DB

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#1527]
### Description of Issue
Run the IEEE123 simulation with the sample app. Then query the time series db for input commands through the stomp client. I only get input commands for one object “939CA567-AA3D-4972-AABC-1D0AAF4859FE”., but there should be 3 other ShuntCompensator.sections object input commands:
'_CABBC3A1-66F5-4B9C-ACB9-476E2389D119'
'_D6C44FF1-BC60-49D3-9438-DFAD1AED0A28'
'_3DE55D2D-34D3-487E-9D6E-3A4DB1E38E47’

goss.gridappsd.process.request.data.timeseries
 
{"queryMeasurement": "simulation",
"queryFilter": {"simulation_id":"1763926368",
"hasSimulationMessageType": "INPUT"},
"responseFormat": "JSON"}
 

Result:
[
    {
        "hasMeasurementDifference": "FORWARD",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "775103f7-f46f-4b53-8170-10828d3cd0f1",
        "simulation_id": "1763926368",
        "time": 1622735902,
        "attribute": "ShuntCompensator.sections",
        "value": 0,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "REVERSE",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "775103f7-f46f-4b53-8170-10828d3cd0f1",
        "simulation_id": "1763926368",
        "time": 1622735902,
        "attribute": "ShuntCompensator.sections",
        "value": 1,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "REVERSE",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "6861bd6d-6676-40d8-9eb4-dfb3e00552fb",
        "simulation_id": "1763926368",
        "time": 1622735917,
        "attribute": "ShuntCompensator.sections",
        "value": 0,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "FORWARD",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "6861bd6d-6676-40d8-9eb4-dfb3e00552fb",
        "simulation_id": "1763926368",
        "time": 1622735917,
        "attribute": "ShuntCompensator.sections",
        "value": 1,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "FORWARD",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "37c7880e-8ea1-42af-b9d0-72999ecd77fa",
        "simulation_id": "1763926368",
        "time": 1622735932,
        "attribute": "ShuntCompensator.sections",
        "value": 0,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "REVERSE",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "37c7880e-8ea1-42af-b9d0-72999ecd77fa",
        "simulation_id": "1763926368",
        "time": 1622735932,
        "attribute": "ShuntCompensator.sections",
        "value": 1,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "REVERSE",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "50cec1d9-3005-41e6-8bad-e6a5aab1ad63",
        "simulation_id": "1763926368",
        "time": 1622735947,
        "attribute": "ShuntCompensator.sections",
        "value": 0,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "FORWARD",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "50cec1d9-3005-41e6-8bad-e6a5aab1ad63",
        "simulation_id": "1763926368",
        "time": 1622735947,
        "attribute": "ShuntCompensator.sections",
        "value": 1,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "FORWARD",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "cc05edb5-979a-4853-ad92-f65864bad651",
        "simulation_id": "1763926368",
        "time": 1622735962,
        "attribute": "ShuntCompensator.sections",
        "value": 0,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "REVERSE",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "cc05edb5-979a-4853-ad92-f65864bad651",
        "simulation_id": "1763926368",
        "time": 1622735962,
        "attribute": "ShuntCompensator.sections",
        "value": 1,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "REVERSE",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "76661ba8-1d28-4c08-be37-5bb65ec5b124",
        "simulation_id": "1763926368",
        "time": 1622735977,
        "attribute": "ShuntCompensator.sections",
        "value": 0,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "FORWARD",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "76661ba8-1d28-4c08-be37-5bb65ec5b124",
        "simulation_id": "1763926368",
        "time": 1622735977,
        "attribute": "ShuntCompensator.sections",
        "value": 1,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "REVERSE",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "52aa111b-00fd-4a6e-8a7c-6959cd7aaf6b",
        "simulation_id": "1763926368",
        "time": 1622735992,
        "attribute": "ShuntCompensator.sections",
        "value": 1,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    },
    {
        "hasMeasurementDifference": "FORWARD",
        "hasSimulationMessageType": "INPUT",
        "difference_mrid": "52aa111b-00fd-4a6e-8a7c-6959cd7aaf6b",
        "simulation_id": "1763926368",
        "time": 1622735992,
        "attribute": "ShuntCompensator.sections",
        "value": 0,
        "object": "_939CA567-AA3D-4972-AABC-1D0AAF4859FE"
    }
]
![Screen Shot 2021-06-03 at 10.04.12 AM.png](https://images.zenhubusercontent.com/5877b6f951aa2c305771faa7/c73e60ca-7978-45f5-890c-5f701169fde7)![Screen Shot 2021-06-03 at 9.58.27 AM.png](https://images.zenhubusercontent.com/5877b6f951aa2c305771faa7/67046f48-3f5e-469c-97c4-80e9af0257c7)

**Comment by ericstephan** [comment]
@Jeffrey-Simpson - I have corrected the problem and checking in the code this afternoon.
