### ISSUE TITLE
Document how to change Blazegraph port on local install

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/GOSS-GridAPPS-D#1537]
Some users are reporting port sharing issues with other programs that are already using :8889 which causes Blazegraph container to error when starting. 

Need to document how to change the port in docker-compose and any other locations needed.

**Comment by tonya1** [comment]
Unfortunately we cannot support updates to the blazegraph port at this time.

**Comment by AAndersn** [comment]
Closing this issue. Will reopen if blazegraph port is made configurable. No documentation needed at current time
