### ISSUE TITLE
Run PNNL campus model within platform

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1542]

**Comment by temcdrm** [comment]
This has been implemented on Stash.

**Comment by poorva1209** [comment]
@temcdrm Does this mean I can import PNNL campus model in GridAPPS-D and run a simulation end-to-end with say sample-app?

**Comment by temcdrm** [comment]
See my email under separate cover.  There are some dependencies on pull requests that haven't been merged yet.
