### ISSUE TITLE
SDGE feeder model not solving with fault_check object

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1566]
The fault_check object is used in the model_startup.glm inside the platform. This is creating an issue when starting the simulation inside the platform. However, the model solves offline with GridLAB-D. Frank is looking into the model and it seems like a GridLAB-D issue.

**Comment by poorva1209** [comment]
Bug fixed in 2022.01.0 that fixes this issue.
Need to be tested with March release 2022.

**Comment by AAndersn** [comment]
This was resolved with a custom exception to remove fault_check for this particular feeder based on its feeder mRID. Closing as "won't fix" due to end of project
