### ISSUE TITLE
Timeseries DB throws error when querying for simulation data

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/GOSS-GridAPPS-D#1571]
I am trying to query Timeseries DB for measurements from an ongoing simulation and getting an internal server error message:

From STOMP Client:

topic: `goss.gridappsd.process.request.data.timeseries`

message: ```{"queryMeasurement": "simulation",
"queryFilter": {"simulation_id": "582881157"},
"responseFormat": "JSON"}```

![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/865b5a28-e594-4f72-bbde-6333e73582a9)

From Python script:

![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/77f27207-5e75-4699-ad28-d1495e8e1192)

**Comment by poorva1209** [comment]
@AAndersn Adding starttime endtime would get me the response : {"queryMeasurement": "simulation", "queryFilter": {"simulation_id": "1190203497","starttime":1638255962000000000, "endtime":1638255962000000000}, "responseFormat": "JSON"}

Can you try this?

**Comment by poorva1209** [comment]
@AAndersn Did you give it a try ?

**Comment by AAndersn** [comment]
Could not trace source of error. Same query text now produces correct Timeseries API response

**Comment by AAndersn** [comment]
@xcosmos6 is having the same issue. 

I also had the same issue occur today, but restarting the platform resolved. 

Restarting the platform is not working for Heng.

**Comment by AAndersn** [comment]
Closing this issue again. Restarting the platform with `./stop.sh -c` worked
