### ISSUE TITLE
Exciting current for transformers exported incorrectly in CIM

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1574]
During CIM export, the exciting current for transformers is exported as magnetizing current. The following image shows that for a given test feeder, there is a shunt resistive branch (given by nll), however, with a zero exciting current. 

![image](https://user-images.githubusercontent.com/35777492/144479085-c5e4b9d3-cbfd-4a31-aa70-ef5214b0958a.png)

**Comment by temcdrm** [comment]
FWIW, there were compensating errors.  OpenDSS exported the magnetizing current as exciting current, and then CIMHub wrote the exciting current as magnetizing current.  Before and after power flow solutions would match. After fixing this issue, the before and after power flow results are not expected to change.

**Comment by temcdrm** [comment]
fixed by https://github.com/GRIDAPPSD/CIMHub/commit/33a69d43464c6e6c8bb2653464b541e78b5633e9 and https://sourceforge.net/p/electricdss/code/3348/ There won't be any impact on the power flow results.
