### ISSUE TITLE
TransformerTank measurement objects not handled correctly

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/GOSS-GridAPPS-D#1590]
Measurements are currently defined for PowerTransformer but not for TransformerTank. 

This issue affects all split-phase customer transformers and regulator banks.

Current models in platform do not have any TransformerTank measurements defined.

When a TransformerTank measurements is attempted to be loaded, the platform throws error below:

![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/f9cb50bd-b471-4962-904f-9476ddfa5e0f)

![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/61e581a4-377f-4106-8b2f-027e89f8f722)

**Comment by poorva1209** [comment]
This was an issue with IEEE123 transactive model. It can be closed right now because @temcdrm commented out Transformer measurements.  Same as #1102 .
