### ISSUE TITLE
Implement Multi-Area State Estimator Prototype

### ISSUE THREAD

**Issue by garydblack** [GRIDAPPSD/GOSS-GridAPPS-D#1601]
Implement a file-based (no GridAPPS-D integration yet) prototype multi-area state estimation capability.  This is based off the methodology proposed in the PES general meeting conference paper (Fernando lead author) and the Julia weighted least squares optimization code developed with the JuMP numerical modeling module.

**Comment by poorva1209** [comment]
@garydblack Can we close this?

**Comment by garydblack** [comment]
Basic prototype is functional minus determining the best data exchange methodology between zones.  Given change of mission of GridAPPS-D and MASE no longer being funded as a result, further work is OBE.
