### ISSUE TITLE
Fix overlapping equipment in Viz

### ISSUE THREAD

**Issue by AAndersn** [GRIDAPPSD/GOSS-GridAPPS-D#1617]
Some adjacent equipment are displayed on top of each other with no connecting line

Example shown on 9500 node model:

![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/6e224e84-95cf-491d-b129-12f04e9b1f14)

![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/3d1fd51b-f634-4c8d-bc5b-9c76cc9a66f8)

This is how the equipment should appear
![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/eb8f6dd9-5b34-4c3a-8c24-9dba4ec6f464)

This one does display correctly:
![image.png](https://images.zenhubusercontent.com/5d51de4956d3534821f8f9ce/155ee704-f26f-46e5-92d5-e75ed232928d)

**Comment by ShuhaoBai** [comment]
Pushed the fix and created a PR for review : https://github.com/GRIDAPPSD/gridappsd-viz/pull/445
