### ISSUE TITLE
Load Demand plot in Viz

### ISSUE THREAD

**Issue by shpoudel** [GRIDAPPSD/GOSS-GridAPPS-D#1640]
The load demand plot in the viz looks incorrect. For the IEEE 123-bus feeder model, the nominal load is ~**3500+1920j (kW+kVAR)**. However, the plot shows a different value (See the attached plot). Also, the y-label of the plot is confusing. With KVA as the label, it is difficult to interpret the "EnergyConsumer p" and "EnergyConsumer q".

![image](https://user-images.githubusercontent.com/35777492/164293439-f0d40505-43f7-4975-af52-60f26c1cdcb9.png)

**Comment by bibiraju** [comment]
@shpoudel We are plotting the sum of all measured energyConsumer p and sum of all energyConsumer q. Similarly for solar panel and battery. Let me know if we need to change it

**Comment by bibiraju** [comment]
Please look at https://github.com/GRIDAPPSD/gridappsd-viz/blob/master/client/src/app/simulation/measurement-chart/MeasurementChartContainer.tsx
Line 312 shows how we filter energyconsumer. Check function _calculatePQValues() to see the calculation.

**Comment by shpoudel** [comment]
if (measurement.conductingEquipmentType === ConductingEquipmentType.EnergyConsumer) is collecting all possible measurements for energyconsumer, shouldn't we also have one filter for "measurement.type === MeasurementType.POWER" before evaluating p and q? I am happy to chat over a call. Sorry, I am not familiar with this language, and please don't fully trust me on this.
