### ISSUE TITLE
Static Ybus service platform integration

### ISSUE THREAD

**Issue by garydblack** [GRIDAPPSD/GOSS-GridAPPS-D#1650]
Need to get the App Toolbox Static Ybus service integrated with the GridAPPS-D platform.  Here are the basics:

* Exists in the gridappsd-toolbox repo under the static-ybus directory

* I have created a gridappsd-static-ybus-service.config file based on Alex's gridappsd-topology-daemon.config.  Both are "launch_on_startup" processes that don't take any arguments.

-Gary

**Comment by garydblack** [comment]
Note that Dynamic Ybus invokes Static Ybus as a request/response service and therefore Static Ybus should be integrated with the platform first in order to be able to test Dynamic Ybus.

Once these are integrated with the "develop" platform release, let me know and I can test them out to make sure they are working correctly.

**Comment by tonya1** [comment]
@garydblack Please test with the container gridappsd/gridappsd:gridappsd-toolbox and approve the pull request if it works as expected.

https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/1656
