### ISSUE TITLE
Dynamic Ybus service platform integration

### ISSUE THREAD

**Issue by garydblack** [GRIDAPPSD/GOSS-GridAPPS-D#1651]
Need to get the App Toolbox Dynamic Ybus service integrated with the GridAPPS-D platform.  Here are the basics:

* Exists in the gridappsd-toolbox repo under the dynamic-ybus directory

* I have created a gridappsd-dynamic-ybus-service.config file based on Alex's gridappsd-topology-service.config.  Both run in the context of a simulation.

-Gary

**Comment by garydblack** [comment]
Note that Dynamic Ybus invokes Static Ybus as a request/response service and therefore Static Ybus should be integrated with the platform first in order to be able to test Dynamic Ybus.

Once these are integrated with the "develop" platform release, let me know and I can test them out to make sure they are working correctly.

**Comment by tonya1** [comment]
@garydblack Please test with the container gridappsd/gridappsd:gridappsd-toolbox and approve the pull request if it works as expected.

https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/pull/1656
