### ISSUE TITLE
Load a saved simulation configuration through the viz

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#1652]
### Description of Issue

Allows a researcher to load a saved configuration and tweak parameters a bit from a previously saved configuration.  The researcher can also send his simulation config to another researcher and the configuration will be easily loaded.

Note this is different than comparing the configurations

**Comment by ShuhaoBai** [comment]
Finished task, tested it and merged to develop branch.
