### ISSUE TITLE
total feeder head power less than the total load

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#1702]
Reported by @vmotakat : 

I am trying to plot total PV power, Total load, and Total Feeder head Active power. I am getting total feeder head power less than the total load in my case for the reduced Southern Feeder when I am trying to working with FRS. Interesting thing is Total active power in OpenDSS model without having PV matching to the total feeder head in GridAPPS-D platform with PV power zero. Not able to find why I am getting load power greater than the feeder head power. I am using the following API or quarries to pull data from the feeder simulation.

def get_all_nodes(gapps, model_mrid):
    QueryNodeMessage="""
        PREFIX r:  [http://www.w3.org/1999/02/22-rdf-syntax-ns#](https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23&data=05%7C01%7CPoorva.Sharma%40pnnl.gov%7Cc13228f463764187b8f408db1b4c6aef%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C638133787244100279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=PGKS4%2BNQX%2BPtE6Kmnp5n6Bf9S5YeFarl8hqfJBIwhzk%3D&reserved=0)
        PREFIX c:  [http://iec.ch/TC57/CIM100#](https://gcc02.safelinks.protection.outlook.com/?url=http%3A%2F%2Fiec.ch%2FTC57%2FCIM100%23&data=05%7C01%7CPoorva.Sharma%40pnnl.gov%7Cc13228f463764187b8f408db1b4c6aef%7Cd6faa5f90ae240338c0130048a38deeb%7C0%7C0%7C638133787244100279%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=prYV0fwRtAZ8wuBPhcYM285GUUl8RmhULQsH55jdne8%3D&reserved=0)
        SELECT DISTINCT ?busname ?cnid ?tpnid (group_concat(distinct ?nomu;separator="") as ?nomv ) WHERE {
        SELECT ?busname ?cnid ?tpnid ?nomu WHERE {
        VALUES ?fdrid {"%s"}
        ?fdr c:IdentifiedObject.mRID ?fdrid.
        ?bus c:ConnectivityNode.ConnectivityNodeContainer ?fdr.
        ?bus c:ConnectivityNode.TopologicalNode ?tp.
        ?bus r:type c:ConnectivityNode.
        ?bus c:IdentifiedObject.name ?busname.
        ?bus c:IdentifiedObject.mRID ?cnid.
        ?fdr c:IdentifiedObject.name ?feeder.
        ?trm c:Terminal.ConnectivityNode ?bus.
        ?trm c:Terminal.ConductingEquipment ?ce.
        
        OPTIONAL {
        ?ce  c:ConductingEquipment.BaseVoltage ?bv.
        ?bv  c:BaseVoltage.nominalVoltage ?nomu.
          }
        bind(strafter(str(?tp), str([http://localhost:8889/bigdata/namespace/kb/sparql#](http://localhost:8889/bigdata/namespace/kb/sparql))) as ?tpnid)
        } ORDER by ?busname
        } 
        GROUP by ?busname ?cnid ?tpnid 
        ORDER by ?busname
        """%model_mrid

    results = gapps.query_data(query = QueryNodeMessage, timeout = 180)
    NodeQuery = results['data']['results']['bindings']
    return NodeQuery

  plot_P_Load=[]
        ss=0
        for index1 in range(len(self.Load_Meas_NodeQuery)): 
            meas_item = self.Load_Meas_NodeQuery[index1]
            meas_mrid=meas_item['measid']['value']
            meas_name=meas_item['eqname']['value']
            
            p = meas_value[meas_mrid]
            der_P_C = np.cos(p['angle']*3.1415/180) * p['magnitude']/1000000
            
            #print('meas_item',meas_name,'Value',der_P_C)
            ss += der_P_C
            plot_P_Load.append(der_P_C)

I am seeing this issue in model conversion and from GridAPPS-D API.

**Comment by poorva1209** [comment]
We will be discussing this in the work meeting today.

**Comment by vmotakat** [comment]
Hi,

The found issue is mainly due to multiple loads on one bus. I have many such cases in the feeder. 
[fdr_output1234.csv](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/10876740/fdr_output1234.csv)

It seems like the issue from query or API. 


![Results_Analysis](https://user-images.githubusercontent.com/102381298/222590692-2c9e509e-2812-4228-bda3-f8afabb8852d.JPG)

Let me know if this correct?

**Comment by shpoudel** [comment]
Venkat will change the source file to fix the issue.
