### ISSUE TITLE
ReadTheDocs FNCS section has Markdown syntax/tags in it.

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#190]
The read the docs Installing GridAPPS-D page the FNCS sections has Markdown tags in it. Maybe did not get converted from Markdown correctly.

[ReadTheDocs](http://gridappsd.readthedocs.io/en/releases-0.1/installing_gridappsd/index.html)

**Comment by AAndersn** [comment]
Old issue. no longer relevant
