### ISSUE TITLE
Write unit tests for web sockets API

### ISSUE THREAD

**Issue by fstshrk** [GRIDAPPSD/GOSS-GridAPPS-D#199]
This needs to be assigned to Erin

**Comment by fstshrk** [comment]
Please work with Craig to determine the requirements.

**Comment by poorva1209** [comment]
@bibiraju One of the 3 tests failed. Please see the screenshot attached.
![image](https://user-images.githubusercontent.com/6538501/30183128-19062be2-93ce-11e7-870e-e3533817122c.png)

**Comment by bibiraju** [comment]
can you do one more install and try npm test again. Looks like it's missing the jest typescrit library
npm install --save-dev ts-jest @types/jest
