### ISSUE TITLE
Update Visualization XY Coordinates

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#203]
In RC1, XY coordinates were available for each node. However, this reflected a legacy use of the CIM Terminal.sequenceNumber attribute, which had been removed from CIM. Instead, the CIM now defines a sequence of XY coordinates for instances of conducting equipment (e.g. line segments, loads, capacitors, regulators). In RC2, we need to render these conducting equipment instances without reference to the nodes.  (NB: the XY coordinates have a sequence, but that sequence doesn't correspond to the Terminals, which don't have a sequence.  Practically, if we render a line segment with two end points, we don't really know which end is which.)

RC2: 

1) change the JSON file of XY coordinates to describe conducting equipment instead of nodes (Tom)
2) change Viz to render conducting equipment instances (Erin/Bibi?)

RC3:

1) should we consider reverse engineering the node coordinates?  This would require a new algorithm.

**Comment by bibiraju** [comment]
Re-opening the issue as the regulators and capacitors are not identified correctly
