### ISSUE TITLE
Create a test user for unit tests

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#215]

**Comment by craig8** [comment]
test_sys_user=1Test,admin,operator,evaluator,testmanager,application,service
test_oper_user=2Test,operator
test_eval_user=3Test,evaluator
test_app_user=4Test,application
test_svc_user=5Test,service

Are the users from https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/blob/develop/gov.pnnl.goss.gridappsd/conf/pnnl.goss.core.security.userfile.cfg

@tonya1 I think we need to discuss organizational usernames/passwords versus how we do testing of different scopes.

**Comment by craig8** [comment]
For permissioned tests, we will have a secret for each combination (test_user_scope="username=password,scope") to be set up as a secret for the gridappsd-test and gridappsd-python projects.

A fixture or function will take the input matching test_user_scope (in above example as key) and set the environment (os.environ) variable such that GRIDAPPSD_USER and GRIDAPPSD_PASSWORD are username and password respectively.

if a fixture we would have a fixture for each test_user_scope entry....if a function we could pass the test_user_scope variable to the function and have it be set.

I think function in conftest.py would be the best place for the function or fixture.
