### ISSUE TITLE
Add alert/events requirement on sharepoint

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#243]
define scope, requirements, and milestone for subscribing and query alerts/events from the platform.

**Comment by poorva1209** [comment]
@ronmelton @temcdrm Add sharepoint link here.

**Comment by temcdrm** [comment]
https://spteams1.pnnl.gov/sites/ADMS/_layouts/WordViewer.aspx?id=/sites/ADMS/Shared%20Documents/ADMS%20Platform%20-%20GM0063/Release%20Cycles/RC4/Alarms_API.docx&Source=https%3A%2F%2Fspteams1%2Epnnl%2Egov%2Fsites%2FADMS%2FSitePages%2FHome%2Easpx%3FRootFolder%3D%252Fsites%252FADMS%252FShared%2520Documents%252FADMS%2520Platform%2520%252D%2520GM0063%252FRelease%2520Cycles%252FRC4%26FolderCTID%3D0x01200031046DD59799534EBF37226738272BB6%26View%3D%7BF520827E%2D9257%2D4A93%2D891A%2DFD278CDD044B%7D&DefaultItemOpen=1&DefaultItemOpen=1
