### ISSUE TITLE
CIM Extension for State Variables

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#249]
Work with Margaret Goodrich to present the attached proposal to WG13, and shepherd through the approval process.
![statevariables](https://user-images.githubusercontent.com/8473679/30185196-5b694e5e-93d5-11e7-8264-6f58c1f0ef31.png)

Initial email correspondence follows
=========
Thanks, Margaret.  A discussion is probably necessary.  For example, power flow algorithms generally solve for current and voltage. I’m not aware of any exceptions.  The power flow values in a display/report are actually the derived quantities, computed after the solution has converged.
 
A simpler question: does Terminal actually have a phases attribute?  My EA file doesn’t have this, and I thought that phases were on the conducting equipment instead.  Maybe the phases attribute was added back in later?  My CIMug invoice just came to PNNL for payment this morning, so I’ll be able to get new EA files shortly.
 
_________________________
 
Tom McDermott, Ph.D., PE, FIEEE
Chief Engineer, Integration
Electricity Infrastructure
Pacific Northwest National Laboratory
Phone: 509-375-4434
Thomas.McDermott@pnnl.gov
 

Tom,
 
Please see the response from Chuck.  Since Chuck is on WG13, I wanted to run this past him before I submit it to WG13 in Oct.  I have asked Chuck if he would be willing to have an extended discussion with you on this before the Oct. meeting.  If so, do you want me to set up a meeting for the 3 of us to talk?
 
Regards,
Margaret E. Goodrich
Cell: 903-477-7176
margaret@j-mgoodrich.com
 
From: DUBOSE III, Charles [mailto:charles.dubose@siemens.com] 
Sent: Wednesday, September 6, 2017 11:33 AM
To: Margaret Goodrich <Margaret@j-mgoodrich.com>
Subject: RE: CIM State Variables
 
Hey Margaret
 
Please keep in mind that the State Variables are the results of a power flow solution.  They are indifferent to the power flow engine used to produce them.  Measurements or the source of the data are not a concern to these attributes and classes. 
 
The SvCurrent attributes would be found on a report or a screen that massages results for the software user.  The current flow would be a result of the calculation of the solved voltage and power flow.  We do not even promote or consider it necessary to provide SvPowerFlow instances on AcLineSegments or PowerTransformers.  These values can be also derived from the voltage and angle on the adjacent TopologyNodes.  So this further removes the current flow from the State Variables.  We were looking for the least number of attributes to describe a power flow solution.
 
SvStatus.inService is a generic status of conducting equipment whether it be a ACLineSegment or a Switch.  The inService attribute works in all instances of conducting equipment.  This also accommodates models which do not have switches.  This is why we did not have two different classes to describe the status of switches and another to describe the status of the rest of the conducting equipment.
 
I would propose a Phase attribute included on the StateVariable or maybe a new class in the inheritance path of the StateVariable classes that require the attribute.    Keep in mind that the Terminal has a phases attribute also.  I think we may have to address the multiplicity of the SV classes to Terminal for the unbalanced values.  For example multiple SvPowerFlow on a three phase energy consumer.  This would be a case where there could be three SvPowerflow instances to a single terminal which has a phases attribute set to “ABCN”  This could do with some discussion.
 
 
Best Regards
Chuck
 
From: Margaret Goodrich [mailto:Margaret@j-mgoodrich.com] 
Sent: Friday, September 01, 2017 6:11 PM
To: DUBOSE III, Charles (RC-US EM DG PTI)
Subject: FW: CIM State Variables
 
Chuck,
 
Please read below and look at the attached.  I hope to submit this to WG13 for consideration but I wanted to run it by you first.
 
Regards,
Margaret E. Goodrich
Cell: 903-477-7176
margaret@j-mgoodrich.com
 
From: McDermott, Thomas E [mailto:thomas.mcdermott@pnnl.gov] 
Sent: Friday, September 1, 2017 4:11 PM
To: Margaret Goodrich <Margaret@j-mgoodrich.com>
Cc: Sharma, Poorva <Poorva.Sharma@pnnl.gov>; Melton, Ronald B <ron.melton@pnnl.gov>; Fisher, Andrew R <Andrew.Fisher@pnnl.gov>
Subject: CIM State Variables
 
Hi Margaret – it was nice talking with you earlier today, and thanks for your kind offer to help.  Our most pressing need is to extend CIM StateVariables in a way most likely to be adopted.  The attached screen shot is my draft proposal with some color highlights.
 
Brown – adding optional phases for state variables, and a new current measurement.  Mathematically, current is derivable from the existing voltage and power state variables, but for some applications (e.g. a state estimator) it matters which one was actually measured or calculated.  Back to phasing, I’m not sure what the ancestor of SvPhase should be.
 
Green – I’m wondering if SvStatus could apply to switches, or if we need a new state variable class for that.  A switch’s open status is a Boolean value, but the attribute name for SvStatus::inService doesn’t really match.
 
Eventually we need to look at SCADA and Measurement packages, but this should do for now.  Can you let me know what you think about the StateVariables?
 
Thanks,
 
_________________________
 
Tom McDermott, Ph.D., PE, FIEEE
Chief Engineer, Integration
Electricity Infrastructure
Pacific Northwest National Laboratory
Phone: 509-375-4434
Thomas.McDermott@pnnl.gov

**Comment by ericstephan** [comment]
Hi Tom,

Beyond the UML diagram do you have additional detail provided in an EA
project (eap) file?  I'd like to work with you to begin organizing and
detailing this out a bit.  Also I'll look into the CIMug site on whether
this constitutes a new module.

Eric

**Comment by temcdrm** [comment]
Superseded by the move to CIM v17 and use of Meas module
