### ISSUE TITLE
Add Events to Test Manager processing

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#257]
Added Events that are being discussed with the Evaluation team and the application developers to the processing done by the Test Manager.

**Comment by AAndersn** [comment]
@Jeffrey-Simpson - This looks like a very old issue. Can we close it?

**Comment by Jeffrey-Simpson** [comment]
Hello,
That looks very old. Yes please.
Thanks,
-Jeff
From: Alexander Anderson ***@***.***>
Reply-To: GRIDAPPSD/GOSS-GridAPPS-D ***@***.***>
Date: Tuesday, August 10, 2021 at 11:52 AM
To: GRIDAPPSD/GOSS-GridAPPS-D ***@***.***>
Cc: "Simpson, Jeff" ***@***.***>, Mention ***@***.***>
Subject: Re: [GRIDAPPSD/GOSS-GridAPPS-D] Add Events to Test Manager processing (#257)


CAUTION: This email originated from outside of NREL. Do not click links or open attachments unless you recognize the sender and know the content is safe.

@Jeffrey-Simpson<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FJeffrey-Simpson&data=04%7C01%7CJeff.Simpson%40nrel.gov%7C92e3a64272154d1cf0eb08d95c279f68%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637642147527541421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YJGemoO2oUKQh8RJ%2FFtPZVIu18lh5YJsxfrj7%2Bz5bI4%3D&reserved=0> - This looks like a very old issue. Can we close it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FGRIDAPPSD%2FGOSS-GridAPPS-D%2Fissues%2F257%23issuecomment-896192461&data=04%7C01%7CJeff.Simpson%40nrel.gov%7C92e3a64272154d1cf0eb08d95c279f68%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637642147527541421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=9GxKMqz8tMblPNz6S1FZZ4k293ikdT0JKa3kz2qPDkM%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAFSH6WE67TNVXN5JILI6573T4FRN3ANCNFSM4D36O2JQ&data=04%7C01%7CJeff.Simpson%40nrel.gov%7C92e3a64272154d1cf0eb08d95c279f68%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637642147527551383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=MZqUVbPTkeX05ns24w6DpARnNXRtvNOhAqbx4y5YiZw%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CJeff.Simpson%40nrel.gov%7C92e3a64272154d1cf0eb08d95c279f68%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637642147527551383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r%2FAsNLi3y6mmHhLL0NMYbStiMoGO2WfQK%2BCVRBNJMLE%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7CJeff.Simpson%40nrel.gov%7C92e3a64272154d1cf0eb08d95c279f68%7Ca0f29d7e28cd4f5484427885aee7c080%7C0%7C0%7C637642147527551383%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZHptqx8wbM70owqDH%2BiyffKUy4B1MHIs7lnjR1cChE0%3D&reserved=0>.
