### ISSUE TITLE
Splice in SCADA/State Estimator Data Flows

### ISSUE THREAD

**Issue by temcdrm** [GRIDAPPSD/GOSS-GridAPPS-D#348]
The State Estimator needs to 1) run as a service, 2) subscribe to measurements and 3) publish estimated values within the platform

**Comment by temcdrm** [comment]
In addition, this issue includes noise generation and sensor-level data processing (e.g. averaging and peak-holding voltages over 5-minute intervals).

**Comment by areiman** [comment]
The intent of this epic has been fulfilled. The state estimator can run as a service, receive measurements, and publish results.

Two issues remain open for other reasons and will be decoupled from this epic; specifically:
 - #598 : This issue will remain open to track eventual full integration with the run-docker.sh script
 - #597 : This issue will remain open until the format for state estimator output is fully specified and implemented.

**Comment by updADMS** [comment]
Good day, Sir

May I ask how can the results of the state estimator be published? It seems that even though state-estimator has been added as a service in gridappsd/services, when I run a simulation in gridappsd platform, I cannot find any output coming from this specific service

Im running v2019.12.0

Thank you
