### ISSUE TITLE
Check R license use to be interfaced in GridAPPS-D

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#376]
- Talk to Peter
- Can we have R with the platform (GNU-GPL, Not safe)
- Contamination ?

Brandon has an application in R.

**Comment by ronmelton** [comment]
Based on discussions via e-mail with PNNL legal office and tech transfer office we should avoid interfacing with R.  R licensing has potential to contaminate our GridAPPS-D licensing.  Though a call from one to the other and separate distribution and installation would limit this risk, it might not eliminate it entirely.  For the specific situation that caused us to explore this Brandon has been directed to implement the algorithm developed using R in python with no calls to R.
