### ISSUE TITLE
Prepopulate ProvEn with test simulation data

### ISSUE THREAD

**Issue by ericstephan** [GRIDAPPSD/GOSS-GridAPPS-D#378]

**Comment by ericstephan** [comment]
@poorva1209 - Hi Poorva,  just a gentle reminder I'll need the testing data to get started on this task.

**Comment by ericstephan** [comment]
For those interested.  I’ve documented a process (SimulationTimeSeriesUpload.pptx) for manually uploading simulation input and output data based on the 321.json and 328.json simulation output files Tonya provided last week.  Below is the link to the folder containing the presentation.

Cheers,
 
Eric
 
https://spteams1.pnnl.gov/sites/ADMS/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2Fsites%2FADMS%2FShared%20Documents%2FADMS%20Platform%20%2D%20GM0063%2FRelease%20Cycles%2FRC3%2Fdatabase%2Dhybridization&FolderCTID=0x01200031046DD59799534EBF37226738272BB6&View={AFDD1370-4F74-4E33-AA23-0C54731FE691}

**Comment by iut62elec** [comment]
Hi Eric. I am interested, but the link needs user/pass. Can you please send me the link that works or user/pass. Thanks for sharing.

Pedram

**Comment by ericstephan** [comment]
Hi Pedram,

Sorry I uploaded to a place not accessible externally.  Attached is the
presentation.  Let me know if you have trouble accessing it.

Cheers,

Eric Stephan

**Comment by iut62elec** [comment]
Hi Eric:

Sorry, I don't see any attachment in your last comment.  Can you email it to me? ('pedram.jahangiri' AT 'nationalgrid' dot com 

Thanks,
Pedram

**Comment by ericstephan** [comment]
Hi Pedram,

I sent you an attachment through my work email.  Let me know if you don't
see if or if you have any questions.  Keep in mind that this is preliminary
work that will be enhanced in the near future when we get our new sample
input and output message formats linked to the simulations.
