### ISSUE TITLE
Identify initial data hybridization configuration to support simulation message testing

### ISSUE THREAD

**Issue by ericstephan** [GRIDAPPSD/GOSS-GridAPPS-D#390]

**Comment by telsethag** [comment]
* Proven integration and required services 
* Data store configurations (semantic & time-series)
* Proven message <--> Gridapps-D message mapping
* Time series schemas and default retention policies
* Reference model integration

**Comment by telsethag** [comment]
Documentation added to gridappsd sharepoint site
