### ISSUE TITLE
Look into getting OSIsoft PI license (possibly developer license) at PNNL

### ISSUE THREAD

**Issue by ericstephan** [GRIDAPPSD/GOSS-GridAPPS-D#415]
Tom, Bibi, Todd, and Eric met with Avista to discuss their smart meter data.  PNNL can get access to their data if we have a PI installation at PNNL.  Tom mentioned this could be an opportunity to explore interoperability.

**Comment by ronmelton** [comment]
We have a license at PNNL.  Greg Dayley and Jeff Banning can provide details.
