### ISSUE TITLE
Create demonstration script

### ISSUE THREAD

**Issue by erinb545** [GRIDAPPSD/GOSS-GridAPPS-D#42]
Create a script for the April 27, 2017 demonstration.

Use a storyboard format.
Highlight the major functions of platform, focusing not on the specific application or visualization, but on the platform developers will use to create/deploy (?) applications.

**Comment by erinb545** [comment]
[FY17DemoStoryboard.pdf](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/848608/FY17DemoStoryboard.pdf)

**Comment by erinb545** [comment]
Updated the storyboard:

- Inserted a step for configuring the platform at the beginning
- Split the terminal window into two windows: Terminal and Log View

[FY17DemoStoryboard_v2.pdf](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/868923/FY17DemoStoryboard_v2.pdf)

**Comment by ronmelton** [comment]
Version 2 of script reviewed - looks good.
