### ISSUE TITLE
shouldn't need to include :

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#479]
When using a tag with the run script you shouldn't need to enter the : before the tag...docker using the tag as anything after the : so we should use the same thing...

````
# should be
run.sh -t dev

# not
run.sh -t :dev
````

**Comment by craig8** [comment]
```` bash
vbox@vbox-VirtualBox ~/git/gridappsd-docker $ ./run.sh -t :dev
Error changing tag from rc3 to dev
Exiting 
````

not sure what this is all about either

**Comment by tonya1** [comment]
It should be 
./run.sh -t dev

The code inserts the : 

   t) # Pass gridappsd tag to docker-compose
      GRIDAPPSD_TAG=":$OPTARG"


The run script also tries to prevent you from changing the version without removeing the existing containers.  I can add a message to remove your containers before chainging.
