### ISSUE TITLE
Identify measurements that need to plot on Viz for all models.

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#494]
Currently we are plotting measurement for just IEEE8500 but if user selects other model then what measurements needs be to plotted. Just pick 3 for version 1.0. 

Later we can make plot measurements selection more custom.

**Comment by temcdrm** [comment]
Bibi to review:

From the "measurements" section of each *dict.json file, plot the following:

1) Capacitor bank open/close state, voltage, and reactive power: the "name" starts with LinearShuntCompensator, and the "measurementType" will be "PNV" for voltage, "Pos" for open/close state, and "VA" (imaginary part) for the reactive power. There will be separate "phases" attributes of A, B and C for each phase of the capacitor bank.  There should be capacitor banks in each of the four models.

2) voltage regulator tap positions. The "name" starts with "RatioTapChanger" and the "measurementType" will be "Pos" with separate "phases" attributes of A, B and C. There should be voltage regulators in each of the four models.

3) For the ieee8500 model only, where the "name" begins with "PowerTransformer_hvmv_sub", plot the PNV and VA measurementType on each phase A, B and C.  There should be 6 altogether.  This gets the voltage and power at the head of the feeder.

**Comment by temcdrm** [comment]
Add these for feeder-head measurements on the other three models.

{"feeders":[
{"name":"ieee123",
"mRID":"_C1C3E687-6FFD-C753-582B-632A27E28507",
"measurements":[
{"name":"ACLineSegment_sw1_Voltage","mRID":"238ed311-7ee5-4ed9-a333-97060b011c3d","ConductingEquipment_mRID":"_7DFABA6A-F79D-38B7-90AD-3D9E349B3922","Terminal_mRID":"_10BAF39F-B139-E5C3-6518-18E21C6B2E44","measurementType":"PNV","phases":"C","MeasurementClass":"Analog","ConductingEquipment_type":"ACLineSegment","ConductingEquipment_name":"sw1","ConnectivityNode":"150r"},
{"name":"ACLineSegment_sw1_Voltage","mRID":"5bc11b5f-000f-4803-b985-0b29dd5c7ee3","ConductingEquipment_mRID":"_7DFABA6A-F79D-38B7-90AD-3D9E349B3922","Terminal_mRID":"_10BAF39F-B139-E5C3-6518-18E21C6B2E44","measurementType":"PNV","phases":"B","MeasurementClass":"Analog","ConductingEquipment_type":"ACLineSegment","ConductingEquipment_name":"sw1","ConnectivityNode":"150r"},
{"name":"ACLineSegment_sw1_Voltage","mRID":"9ebe1ae7-4a12-49e5-92e5-d44c675982d4","ConductingEquipment_mRID":"_7DFABA6A-F79D-38B7-90AD-3D9E349B3922","Terminal_mRID":"_10BAF39F-B139-E5C3-6518-18E21C6B2E44","measurementType":"PNV","phases":"A","MeasurementClass":"Analog","ConductingEquipment_type":"ACLineSegment","ConductingEquipment_name":"sw1","ConnectivityNode":"150r"},
{"name":"ACLineSegment_sw1_Power","mRID":"393ac52f-1cd6-4e67-8cc4-8039b297a070","ConductingEquipment_mRID":"_7DFABA6A-F79D-38B7-90AD-3D9E349B3922","Terminal_mRID":"_10BAF39F-B139-E5C3-6518-18E21C6B2E44","measurementType":"VA","phases":"B","MeasurementClass":"Analog","ConductingEquipment_type":"ACLineSegment","ConductingEquipment_name":"sw1","ConnectivityNode":"150r"},
{"name":"ACLineSegment_sw1_Power","mRID":"5cc2ed2c-b1fd-4b36-a3eb-69472c2dbe14","ConductingEquipment_mRID":"_7DFABA6A-F79D-38B7-90AD-3D9E349B3922","Terminal_mRID":"_10BAF39F-B139-E5C3-6518-18E21C6B2E44","measurementType":"VA","phases":"A","MeasurementClass":"Analog","ConductingEquipment_type":"ACLineSegment","ConductingEquipment_name":"sw1","ConnectivityNode":"150r"},
{"name":"ACLineSegment_sw1_Power","mRID":"e16182a8-fef8-47a1-85fd-4225d3f69d98","ConductingEquipment_mRID":"_7DFABA6A-F79D-38B7-90AD-3D9E349B3922","Terminal_mRID":"_10BAF39F-B139-E5C3-6518-18E21C6B2E44","measurementType":"VA","phases":"C","MeasurementClass":"Analog","ConductingEquipment_type":"ACLineSegment","ConductingEquipment_name":"sw1","ConnectivityNode":"150r"}
]
}]}

{"feeders":[
{"name":"j1",
"mRID":"_67AB291F-DCCD-31B7-B499-338206B9828F",
"measurements":[
{"name":"LoadBreakSwitch_temp_sub_Current","mRID":"5803f7ea-0039-46d6-be3d-0c30d3184639","ConductingEquipment_mRID":"_8EF47603-A810-AECB-EE80-9A15B64B6FF1","Terminal_mRID":"_F908F90A-94A5-5015-2952-BD6DC8E3E100","measurementType":"A","phases":"B","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"temp_sub","ConnectivityNode":"ls_bus"},
{"name":"LoadBreakSwitch_temp_sub_Current","mRID":"7bcfd7ca-16b1-4542-921c-2a90006daf70","ConductingEquipment_mRID":"_8EF47603-A810-AECB-EE80-9A15B64B6FF1","Terminal_mRID":"_F908F90A-94A5-5015-2952-BD6DC8E3E100","measurementType":"A","phases":"A","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"temp_sub","ConnectivityNode":"ls_bus"},
{"name":"LoadBreakSwitch_temp_sub_Current","mRID":"dc71a1cb-a23a-4705-b649-42638b0b27fc","ConductingEquipment_mRID":"_8EF47603-A810-AECB-EE80-9A15B64B6FF1","Terminal_mRID":"_F908F90A-94A5-5015-2952-BD6DC8E3E100","measurementType":"A","phases":"C","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"temp_sub","ConnectivityNode":"ls_bus"},
{"name":"LoadBreakSwitch_temp_sub_Voltage","mRID":"161a3973-c482-4671-b794-e2056e775d3f","ConductingEquipment_mRID":"_8EF47603-A810-AECB-EE80-9A15B64B6FF1","Terminal_mRID":"_F908F90A-94A5-5015-2952-BD6DC8E3E100","measurementType":"PNV","phases":"B","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"temp_sub","ConnectivityNode":"ls_bus"},
{"name":"LoadBreakSwitch_temp_sub_Voltage","mRID":"f68bee5b-6938-420e-950d-6772dbc2501c","ConductingEquipment_mRID":"_8EF47603-A810-AECB-EE80-9A15B64B6FF1","Terminal_mRID":"_F908F90A-94A5-5015-2952-BD6DC8E3E100","measurementType":"PNV","phases":"A","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"temp_sub","ConnectivityNode":"ls_bus"},
{"name":"LoadBreakSwitch_temp_sub_Voltage","mRID":"fc2276fb-09db-4c05-964f-044ba2f3b278","ConductingEquipment_mRID":"_8EF47603-A810-AECB-EE80-9A15B64B6FF1","Terminal_mRID":"_F908F90A-94A5-5015-2952-BD6DC8E3E100","measurementType":"PNV","phases":"C","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"temp_sub","ConnectivityNode":"ls_bus"}
]
}]}

{"feeders":[
{"name":"r2_12_47_2",
"mRID":"_9CE150A8-8CC5-A0F9-B67E-BBD8C79D3095",
"measurements":[
{"name":"LoadBreakSwitch_trunk_Voltage","mRID":"36113c8c-3a24-4410-9e43-89d79486e2cb","ConductingEquipment_mRID":"_33A26201-AFB3-C79A-397A-1358D80C16EE","Terminal_mRID":"_950ADA28-24C0-BFE1-8F90-C2858A53053B","measurementType":"PNV","phases":"C","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"trunk","ConnectivityNode":"sourcebus"},
{"name":"LoadBreakSwitch_trunk_Voltage","mRID":"d77b6b5f-cb3c-4b73-9490-305d31a7a9a4","ConductingEquipment_mRID":"_33A26201-AFB3-C79A-397A-1358D80C16EE","Terminal_mRID":"_950ADA28-24C0-BFE1-8F90-C2858A53053B","measurementType":"PNV","phases":"A","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"trunk","ConnectivityNode":"sourcebus"},
{"name":"LoadBreakSwitch_trunk_Voltage","mRID":"e03ad97a-7a0e-411e-9b06-594ec377e515","ConductingEquipment_mRID":"_33A26201-AFB3-C79A-397A-1358D80C16EE","Terminal_mRID":"_950ADA28-24C0-BFE1-8F90-C2858A53053B","measurementType":"PNV","phases":"B","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"trunk","ConnectivityNode":"sourcebus"},
{"name":"LoadBreakSwitch_trunk_Current","mRID":"9d0072f4-6cbe-4327-b7b9-0315ca87f23f","ConductingEquipment_mRID":"_33A26201-AFB3-C79A-397A-1358D80C16EE","Terminal_mRID":"_950ADA28-24C0-BFE1-8F90-C2858A53053B","measurementType":"A","phases":"C","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"trunk","ConnectivityNode":"sourcebus"},
{"name":"LoadBreakSwitch_trunk_Current","mRID":"cea77584-3377-40f5-8a96-adf4531cc7ef","ConductingEquipment_mRID":"_33A26201-AFB3-C79A-397A-1358D80C16EE","Terminal_mRID":"_950ADA28-24C0-BFE1-8F90-C2858A53053B","measurementType":"A","phases":"A","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"trunk","ConnectivityNode":"sourcebus"},
{"name":"LoadBreakSwitch_trunk_Current","mRID":"e123b16a-0c1d-4472-9c5c-efd41b321fb1","ConductingEquipment_mRID":"_33A26201-AFB3-C79A-397A-1358D80C16EE","Terminal_mRID":"_950ADA28-24C0-BFE1-8F90-C2858A53053B","measurementType":"A","phases":"B","MeasurementClass":"Analog","ConductingEquipment_type":"LoadBreakSwitch","ConductingEquipment_name":"trunk","ConnectivityNode":"sourcebus"}
]
}]}
