### ISSUE TITLE
Build gridappsd subsystem in VOLTTRON

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#539]
As a better integration point between volttron and GridAPPSD rather than a wrapper agent, we are going to build a gridappsd subsystem in VOLTTRON to handle the communication with gridappsd.  Each agent can interact with gridappsd directly through the use of the gridappsd-python package and the subsystem api.

**Comment by poorva1209** [comment]
Not going to be implemented like this
