### ISSUE TITLE
Review and update Software QA Plan (including testing)

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#572]

**Comment by ronmelton** [comment]
Adding Craig

**Comment by ronmelton** [comment]
Craig and Ron discussed the relationship between test plan and QA plan.  Craig has reviewed the test plan and believes that it is fine as currently written. The SW QA plan needs to have references to the test plan updated and other references to GitHub locations etc. updated too.  Craig will make the updates.  Ron will review - then this will be complete.

**Comment by poorva1209** [comment]
To be reviewed by QA persone.
