### ISSUE TITLE
Pipe application and service log file to simulation folder

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#573]
Currently service and app developers have to create and look into a log file to easily view logs specific to their app or service. 
Ideally it should be visible through Viz using simulation Is and log source. 

Work with @Bibi to implement this.

**Comment by craig8** [comment]
Note if this is going to be all logs in the viz I would think that application developers may want to filter based upon app / simulation / database etc.  Perhaps that would be a good thing to look at for this?

**Comment by poorva1209** [comment]
> Note if this is going to be all logs in the viz I would think that application developers may want to filter based upon app / simulation / database etc. Perhaps that would be a good thing to look at for this?

Yes, there will be filters in Viz to filter on log source.

**Comment by poorva1209** [comment]
Closing this issue. It will implemented as #741
