### ISSUE TITLE
Modify documentation of simulation message

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#576]
### Description of Issue
The documentation of the simulation output is incorrect on https://gridappsd.readthedocs.io/en/latest/using_gridappsd/index.html#subscribe-to-simulation-output

The following is what it should/will be (once epoch timestamp) is specified.

````
{
    "simulation_id" : "12ae2345",
    "message" : {
        "timestamp" : "YYYY-MM-DDThh:mm:ss.sssZ",  # note epoch time here
        "measurements" : [
            {
                "measurement_mrid" : "123a456b-789c-012d-345e-678f901a234b",
                "magnitude" : 3410.456,
                "angle" : -123.456
            }
        ]
    }
}
````

**Comment by afisher1** [comment]
I just modified the documentation and committed to the master.
