### ISSUE TITLE
Process Manager is not processing simulation request from Viz

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#590]
### Description of Issue
Request string is not parsing to SimulationRequest Object in NewSimulationRequest class.

**Comment by poorva1209** [comment]
@craig8 I am not able to reproduce the error.
Following code is working for me:
RequestSimulation config = RequestSimulation.parse(message.toString());

I did following to reproduce the error-
1. Cloned fix-epoch-time.
2. Fixed all cim2glm errors 
3. Build gridappsd container
4. Ran gridappsd-docker with gridappsd container

I am using master branch from gridappsd-docker repo.

**Comment by poorva1209** [comment]
@craig8 @afisher1 I do get this error:

java.lang.NullPointerException
	at gov.pnnl.goss.gridappsd.process.ProcessNewSimulationRequest.process(ProcessNewSimulationRequest.java:239)
	at gov.pnnl.goss.gridappsd.process.ProcessEvent.onMessage(ProcessEvent.java:130)
	at pnnl.goss.core.client.GossClient$1.run(GossClient.java:318)
	at java.lang.Thread.run(Thread.java:748)
Thread-40 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1529358944017|gov.pnnl.goss.gridappsd.process.ProcessNewSimulationRequest|1700056284|ERROR|system|ERROR
Process Initialization error: null

Is this the one that you are getting?

**Comment by craig8** [comment]
yes that's the one.

**Comment by poorva1209** [comment]
Viz is sending request to start sample_app but sample_app is not in the applications folder. That's why it is complaining. I will ask Bibi and Nhuy to display apps in Viz only if platform status returns those apps. 
I will also ask them to not send any applications by default in viz

For now, I can add a better error message and send back to Viz. 
You can test with adding sample_app in applications folder.

**Comment by craig8** [comment]
Can you verify that if you clone the sample app and put it in the apps folder.  I believe I had that already ini the docker-compose.yml file.

**Comment by poorva1209** [comment]
I can see incrementing timesteps but no simulation output which I assume is due to epoch or simulation run issue.

**Comment by poorva1209** [comment]
Pushed my  changes to fix-epoch-time branch
