### ISSUE TITLE
Integrate State Estimator as a Service

### ISSUE THREAD

**Issue by areiman** [GRIDAPPSD/GOSS-GridAPPS-D#598]
### Description of Issue
When enabled, the state estimator should be started by the platform for each simulation. For the demo, the state estimator was built to be run outside of the platform. The state estimator and its configuration file will be updated so that the state estimator is started by the platform by default when the state estimator is included in the docker compose file.

**Comment by areiman** [comment]
This issue to remain open until the state estimator is fully integrated with the platform via run-docker.sh

**Comment by areiman** [comment]
We would like to close this after a "checkbox" has been added to the Viz to enable state estimator with a newly launched simulation. Adding Bibi.

**Comment by poorva1209** [comment]
Issue #96 on board already take care of adding state estimator on Viz. We will track it there. 
Closing this issue.
