### ISSUE TITLE
Create documentation for Java program converting CIM XML to GridLAB-D GLM format.

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#60]
acceptance criteria: 
- [x] provide purpose and api documentation in source code.
- [x] add to readthedocs

@temcdrm , @tdtalbot : Does it require separate document or source code documentation would cover it ?  Update acceptance criteria accordingly.

**Comment by temcdrm** [comment]
Javadoc and in-line comments inserted on Powergrid-models/CIM temcdrm branch

**Comment by poorva1209** [comment]
@craig8 Pull request merge pending.

**Comment by temcdrm** [comment]
linked to readthedocs

**Comment by temcdrm** [comment]
Andy to review
