### ISSUE TITLE
Add version REST API to Proven

### ISSUE THREAD

**Issue by ericstephan** [GRIDAPPSD/GOSS-GridAPPS-D#655]
### Description of Issue
It is currently difficult to determine the current version of Proven GridAPPS-D users are working against.   This proposal is to provide a service that returns the version of the Proven Server running.  This will help overcoming confusion for developers working against the platform that is currently changing.

One approach is to amend information  provide information in the current "status" REST service.   

@telsethag @bibiraju

**Comment by craig8** [comment]
This is a common issue of ALL services...I would amend this to have a response for all of the services.
