### ISSUE TITLE
Expected Results in display in visualization.

### ISSUE THREAD

**Issue by Jeffrey-Simpson** [GRIDAPPSD/GOSS-GridAPPS-D#657]
### Description of Issue
New feature.
Expected Results in display in visualization.

**Comment by bibiraju** [comment]
Can you provide more details on what is expected?

**Comment by Jeffrey-Simpson** [comment]
Hello,
Yes I can. This is place holder issue for now, but we can schedule a meeting and I can provide more detail.
Thanks,
-Jeff

**Comment by Jeffrey-Simpson** [comment]
![image](https://user-images.githubusercontent.com/23363416/43914409-10d493e6-9bc5-11e8-9e1a-be98b720d391.png)

**Comment by Jeffrey-Simpson** [comment]
Table construction:

DROP TABLE IF EXISTS `expected_results`;
CREATE TABLE `expected_results` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `test_id` varchar(255) DEFAULT NULL,
  `process_id` varchar(255) DEFAULT NULL,
  `mrid` varchar(255) NOT NULL,
  `property` varchar(255) NOT NULL,
  `expected` varchar(255) NOT NULL,
  `actual` varchar(255)  NOT NULL,
  `simulation_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8 COMMENT='This table contains messages for expected results';


Sample output:

mysql> select * from expected_results;
+-----+------------+------------+---------------------------------------+-----------+---------------------+---------------------+---------------------+
| id  | test_id    | process_id | mrid                                  | property  | expected            | actual              | simulation_time     |
+-----+------------+------------+---------------------------------------+-----------+---------------------+---------------------+---------------------+
| 422 | sample_app | 1646349208 | _2e0d7858-974f-403e-8631-4da1235f30b5 | angle     | -25.781052149060198 | 20.181440216999917  | 2018-06-20 20:54:03 |
| 423 | sample_app | 1646349208 | _2e0d7858-974f-403e-8631-4da1235f30b5 | magnitude | 1940888.324566626   | 1747843.5444602773  | 2018-06-20 20:54:03 |
| 424 | sample_app | 1646349208 | _944fad4a-2541-44ff-8f88-0a5aa7a9d659 | value     | 1                   | 0                   | 2018-06-20 20:54:03 |
| 425 | sample_app | 1646349208 | _74653361-3b39-41af-8592-def0653ea623 | value     | 1                   | 0                   | 2018-06-20 20:54:03 |
| 426 | sample_app | 1646349208 | _c00e1902-cd87-4182-8367-c8f0ea97c552 | value     | 1                   | 0                   | 2018-06-20 20:54:03 |
| 427 | sample_app | 1646349208 | _80b4ce92-af77-485c-a8eb-f242f574bc8a | angle     | -26.435534360876314 | 19.882774671730107  | 2018-06-20 20:54:03 |
| 428 | sample_app | 1646349208 | _80b4ce92-af77-485c-a8eb-f242f574bc8a | magnitude | 1841123.2144119646  | 1639738.0754823901  | 2018-06-20 20:54:03 |
| 429 | sample_app | 1646349208 | _42b7689a-0321-43ba-9d4a-0c257ccb23be | value     | 1                   | 0                   | 2018-06-20 20:54:03 |
| 430 | sample_app | 1646349208 | _551a5188-4850-4979-ad18-6c30091e7b57 | value     | 1                   | 0                   | 2018-06-20 20:54:03 |
+-----+------------+------------+---------------------------------------+-----------+---------------------+---------------------+---------------------+
