### ISSUE TITLE
Write overview description and component section in readthedocs.

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#66]
- [x] add 1-2 paragraph of platform overview
- [x] add components diagram (for RC1) with few lines for each component

**Comment by temcdrm** [comment]
in overview section

**Comment by temcdrm** [comment]
Ron to review.  I have a draft ADMS_MYPP from August/September 2016, but apparently not published onto the Web.  If DOE published this MYPP, we should link to it.
