### ISSUE TITLE
Write overview->component section in readthedocs

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#67]
- [x] describe various components in platform (with diagram)
- [x] describe components used in release cycle 1(with diagram)

**Comment by temcdrm** [comment]
under developer_resources, added description of platform modules and CIM

**Comment by temcdrm** [comment]
see developer resources, sections on the CIM and UML diagrams

**Comment by temcdrm** [comment]
Poorva or Tara to review this much.  Not sure if Ron's platform description goes here, or somewhere else.
