### ISSUE TITLE
Resolve measurement query issues 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#672]
### Description of Issue
Jeff facing errors while querying measurements from blazegraph.
There is no output in model_output.json file.

**Comment by temcdrm** [comment]
Can't reproduce.  From the command line, the measurement scripts and CIMImporter produce meas1_base.glm, meas1_dict.json (with measurements) and meas1_symbols.json as expected.

**Comment by Jeffrey-Simpson** [comment]
For feeders added to docker blazegraph container by the build scripts:
The url "http://localhost:9999/blazegraph/namespace/kb/sparql" should be used for inserting measurements.  

For working with new feeders added to docker blazegraph then the url "http://localhost:8889/bigdata/namespace/kb/sparql" should be used for inserting measurements.

I think the url can be determined with a query on a query before insertion, but I am not sure.

**Comment by temcdrm** [comment]
Brandon Thayer encountered this issue before, and created a solution in the Powergrid-Models/Meas/constants.py file.  This file is edited, depending on the context in which it's used.  The CIMImporter.java also has the -u option for this purpose.

**Comment by temcdrm** [comment]
Added a statement about the port numbers to Powergrid-Models/Meas/README.md
