### ISSUE TITLE
Provide references in readtehdocs

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#69]
provide description, installation instructions, build instrcutions, papers and source code references for
- [x] fncs
- [x] gridlabd
- [x] goss
- [x] IEEE 8500 model (default and changes made)

**Comment by temcdrm** [comment]
under developer_resources, added IEEE references for the 8500-node model and the VVO app

**Comment by temcdrm** [comment]
added GLD, GOSS and FNCS papers

**Comment by temcdrm** [comment]
linked in from API documentation (GLD, GOSS, FNCS) and Integrated Applications (VVO, 8500)
