### ISSUE TITLE
Write FNCS side of GOSS-FNCS Bridge

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#7]

**Comment by afisher1** [comment]
I Finished writing the necessary functions the GOSS-FNCS Bridge will need to call to register with the fncs_broker, publish and subscribe to messages on the FNCS message bus, and request the next time step to move to. All I need to do is implement them in the GOSS-FNCS Bridge @poorva1209 has been working on.
