### ISSUE TITLE
Determine a structure for the Proven ReadTheDocs documentation

### ISSUE THREAD

**Issue by telsethag** [GRIDAPPSD/GOSS-GridAPPS-D#728]

**Comment by ericstephan** [comment]
Bibi and I met today to write up an outline for the documentation and assign tasks:

@bibiraju -  update Outline, provide orientation for provenance, work with Eric on the users guide for power grid simulation quick starts, and scientific workflows.

@ericstephan - Write narrative on history of proven, orientation on the hybrid store, work with Bibi on the users guid for power grid simulation quick starts and scientific workflows.

@telsethag Can you be the reviewer?
