### ISSUE TITLE
Insert measurements in customized 123 model (NREL)

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#740]
User can select and view customized model but there are no measurements in the model for simulation output.

**Comment by Jeffrey-Simpson** [comment]
[ieee123_pv_CIM_meas.xml.zip](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/2474887/ieee123_pv_CIM_meas.xml.zip)

Measurements added
