### ISSUE TITLE
Implement Querying Logs in Viz with filters to select source, debug level etc.

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#741]
An example of a table with filters  : https://datatables.net/examples/styling/foundation 

- Send query request at goss.gridappsd.process.request.data.log
- Request message structure:

String source;
	String processId,
	LogLevel logLevel;
	ProcessStatus processStatus;
        String username;

Where:
public enum LogLevel {
		TRACE, DEBUG, INFO, WARN, ERROR, FATAL
	}
	public enum ProcessStatus {
		STARTING, STARTED, RUNNING, ERROR, CLOSED, COMPLETE
	}

**Comment by craig8** [comment]
See #744 for what I think we should do for making it easier for apps to write to the log

**Comment by nhuyvan1106** [comment]
There should be 3 fields to enter for "source", "processId", and "username", and 2 dropdown for "logLevel", and "processStatus" ?
