### ISSUE TITLE
Incorrect handling of regulator taps in fncs_goss_bridge.py 

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#754]
### NOTE
Be sure to read the comments below, as the nature of this issue has changed slightly with the cim100 update.

### Description of Issue
fncs_goss_bridge.py expects integer tap positions (as GridLAB-D wants), but should expect and accept a float per unit voltage (as defined in the CIM).

### Affected Version
develop branch

### Additional Details
@blthayer has written Python code for translating back and forth between GridLAB-D regulator positions and CIM positions. This code should be verified. Here it is:
```python
def reg_tap_cim_to_gld(step, step_voltage_increment):
    """

    :param step: CIM setting of voltage regulator, which is a
                    multiplier of nominal voltage, e.g. 1.0125.

    :param step_voltage_increment: voltage step as multiplier of nominal
                                   voltage, e.g. 0.625

    :return: tap position in GridLAB-D speak, e.g. 10 or -2
    """

    return round((step - 1) * 100 / step_voltage_increment)


def reg_tap_gld_to_cim(tap_pos, step_voltage_increment, ndigits=4):
    """

    :param tap_pos:
    :param step_voltage_increment:
    :return:
    """

    return round(tap_pos * step_voltage_increment / 100 + 1, ndigits)
```
@afisher1 @poorvasharma @temcdrm @craig8

**Comment by blthayer** [comment]
@afisher1 - Is this something you've worked on? I seem to recall you mentioning it, but I'm not sure.

**Comment by blthayer** [comment]
@afisher1 - looking into the source, it seems the TapChanger.step value is simply being forwarded to the simulation with no conversion. Is this fix on the docket?

**Comment by blthayer** [comment]
@afisher1 - with the CIM 100 update, this is still relevant but slightly different. Copying + pasting an example from Skype chat:

say we have a 32 tap regulator
in the CIM, that'll be taps 0 through 32
with 16 being the neutral tap
however, in GridLAB-D, it'll be -16 to 16, with 0 being the neutral tap
so, before forwarding the command to GridLAB-D, it should be shifted to the appropriate range

**Comment by blthayer** [comment]
@poorva1209 - tagging you so you're in the loop. This isn't critical, but is a lurking bug that could cause complications in the future.

**Comment by blthayer** [comment]
A note from @temcdrm:

"Since I was already in OpenDSS, the regulator tap neutral position has been changed from 16 to 0."

While this ensures the CIM and GridLAB-D now agree, to make the fncs_goss_bridge robust it should do the conversion between CIM and GridLAB-D anyways (even if it's currently a "no-op").

**Comment by poorva1209** [comment]
@blthayer Can you test and close this issue. If you have already tested it out, please close this one.

**Comment by blthayer** [comment]
@poorva1209 @afisher1 
I believe things are working now, but it's fragile and hard-coded. Check out lines 603-605:
```python
elif cim_attribute == "TapChanger.step":
    for y in object_phases:
        fncs_input_message["{}".format(simulation_id)][object_name_prefix + object_name][object_property_list[0].format(y)] = x.get("value")
```

Notice that the tap changer step is simply directly passed into the GridLAB-D simulation. GridLAB-D and the CIM **do not** follow the same conventions for defining tap changer positions. However, with @temcdrm's recent change, we're effectively hard-coding regulators to use the same tap range in GridLAB-D and CIM. While this works, we could inadvertently get some really weird and difficult to track down behavior in the future if anything changes.

My understanding is that part of the role of the fncs_goss_bridge is to translate from CIM commands/conventions to GridLAB-D conventions, and the reverse happens for outputs. So, to properly address this issue the fncs_goss_bridge should use regulator attributes from the CIM to convert tap positions to GridLAB-D tap positions. However, right now the value is simply being directly passed through the bridge. I've given functions above that do this translation. 

Does this make sense? If not, I'm happy to pull a quick meeting together to discuss.

**Comment by blthayer** [comment]
Closing this as I've moved it [here](https://github.com/GRIDAPPSD/gridappsd-forum/issues/17#issue-474752262).
