### ISSUE TITLE
Time series database issues when running simulation faster than real time

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#765]
### Description of Issue
I'm in a rush, so this is going to be quick - I can help with more details later.
Three issues:
- [ ] Not receiving all measurements that should be there.
- [x] Receiving duplicate timestamps for a single MRID
- [x] Database timestamps are not using the time I asked the simulation to run for.

### Affected Version
`develop` branch

### Steps to Reproduce
1. Start platform (`develop` branch)
2. In the viz, go to the simulations tab.
    1. Select `ieee8500` for the `Line name`
    2. Change the `Start time` to `2013-01-01 00:00:00`
    3. Uncheck the box to make simulation run faster than real time
    4. Select the `sample_app` from the `Application name` dropdown
    5. Hit `Submit`
3. Run the simulation, wait for completion
4. Go the the `stomp client` tab in the viz.
    1. Change topic to `goss.gridappsd.process.request.data.timeseries`
    2. Paste the following into the request window (update the `simulationId`):

```
{"queryMeasurement": "PROVEN_MEASUREMENT", "queryFilter": {"hasSimulationId": "1877140527", "hasMrid": "_6192e355-7175-4b09-9e5d-0a7ee1c61461"}, "responseFormat": "JSON"}
```
3. Hit `send request`
5. Notice:
    1. There are duplicate measurements/timestamps
    2. There are only six total measurements, but I would expect 120.
    3. The times correspond to today, _not_ 2013.

@poorva1209

**Comment by poorva1209** [comment]
@afisher1 @blthayer 
Platform now uses the timestamp provided in user request for simulation start time and simulation output.

**Comment by poorva1209** [comment]
@blthayer What does _6192e355-7175-4b09-9e5d-0a7ee1c61461 mrid refers too?

**Comment by poorva1209** [comment]
@afisher1 @blthayer Receiving duplicate timestamps for a single MRID - This issue has also been resolved. I think the timestamp updates for using right time in start time and simulation output took care of this too.

**Comment by ericstephan** [comment]
A new rest service was added to the proven-cluster hybrid service to accept JSON messages and the proven client was modified to pass JSON text to the hybrid service.    A lightweight JSON library is now used to process measurements or input criteria.  Queries in Influx still use the same proven-cluster REST API.

**Comment by poorva1209** [comment]
Waiting on PR 800

**Comment by ericstephan** [comment]
Hi @poorva1209 what is PR 800?  Is there something you need from me?

Thanks

**Comment by blthayer** [comment]
@poorva1209 - same situation, my GitHub notifications weren't correctly working, and I didn't see your comments.
Do you need further action from me?
