### ISSUE TITLE
Implement and add Jet disclosure job processing pipelines

### ISSUE THREAD

**Issue by telsethag** [GRIDAPPSD/GOSS-GridAPPS-D#791]
### Description of Issue
Implement default Jet disclosure processing pipelines.  This will include:
* source:disclosure stream -> sink:message stream
* source:disclosure stream -> sink:measurement stream

Integrate new pipelines into disclosure-module and submit in module startup

**Comment by ericstephan** [comment]
@telsethag and @bibiraju Todd,

I think I have walked through the process of using SHACL shapes and most of the elements needed to create a measurement message.  I'm leveraging a MessageUtil function getProvenMeasurement to construct the KnowledgeMessage.   I'm a little concerned about building a parallel code if I just copy the code from MessageUtil into my pipeline.  This is something we may want to discuss tomorrow.

**Comment by telsethag** [comment]
@ericstephan  sounds good, lets discuss this tomorrow.

**Comment by ericstephan** [comment]
I'm building a filter for the raw json message to remove measurements to support Explicit messages.  In the following example (see below) there are two "message" embedded json objects.  I'm not sure how to parse out measurements like these without going to SHACL first and working in the Jena object.

 Going to Jena sounds like an expensive choice just to turn around and remove the measurements.  

Thoughts?

{
	"domain": "gridappsd.pnnl.gov",
	"name": "SimulationInput",
	"content": "measurement",
	"disclosureId": "abc12434",
	"requestorId": "xyz356436",
	"isStatic": false,
	"isTransient": false,
	"message": {
		"command": "update",
		"input": {
			"simulation_id": "12ae2345",
			"message": {
				"timestamp": 1357048800,
				"difference_mrid": "123a456b-789c-012d-345e-678f901a235c",
				"reverse_differences": [{
						"object": "61A547FB-9F68-5635-BB4C-F7F537FD824E",
						"attribute": "ShuntCompensator.sections",
						"value": "1"
					},
					{
						"object": "E3CA4CD4-B0D4-9A83-3E2F-18AC5F1B55BA",
						"attribute": "ShuntCompensator.sections",
						"value": "0"
					}
				],
				"forward_differences": [{
						"object": "61A547FB-9F68-5635-BB4C-F7F537FD824E",
						"attribute": "ShuntCompensator.sections",
						"value": "0"
					},
					{
						"object": "E3CA4CD4-B0D4-9A83-3E2F-18AC5F1B55BA",
						"attribute": "ShuntCompensator.sections",
						"value": "1"
					}
				]
			}

		}
	}
}

**Comment by ericstephan** [comment]
@telsethag @bibiraju 

What if we instead made the outer message "proven_message" ?

	"domain": "gridappsd.pnnl.gov",
	"name": "SimulationInput",
	"content": "measurement",
	"disclosureId": "abc12434",
	"requestorId": "xyz356436",
	"isStatic": false,
	"isTransient": false,
	"proven_message": {

**Comment by ericstephan** [comment]
@telsethag @bibiraju 

Another option might be just to traverse through the map and when encountering a JSONObject not copying those into a new object.

**Comment by telsethag** [comment]
@ericstephan @bibiraju Not sure if I understand the issue here.  Leave key as "message" and extract using json library into a JsonObject, this will be the raw message (i.e. no "meta-data").  IMO shacl/jena should be reserved for T3 data processing (it's expensive, as you've mentioned) and TS data processing should use the json library.  What map are you traversing?

**Comment by ericstephan** [comment]
@telsethag @bibiraju 

Its all good, I added a few methods to the MessageUtils class to clip off the top of the message for the explicit message.  This avoided using Jena.
	

Eric

public  static String getExplicitJsonMessage(String message) {
		
        
 	    JsonReader jsonReader = Json.createReader(new StringReader(message));
        JsonObject obj = jsonReader.readObject();
	    
	    obj.asJsonObject();
	    JsonObjectBuilder exObjBlder = Json.createObjectBuilder();
	    
	    Set<String> keys = obj.keySet();
	     Iterator<String> it = keys.iterator();
	    while (it.hasNext()) {
            String mykey = it.next();
	    	System.out.println(mykey);
	    	if (obj.get(mykey).getValueType() != ValueType.OBJECT) {
		    	exObjBlder.add(mykey, obj.get(mykey));	    		
	    	}
	    
	    }
	    exObjBlder.add("messageObjectSize", getJsonMessageObjectSize(message));
	    exObjBlder.add("messageSize", getJsonMessageSize(message));
	    JsonObject explicitObject = exObjBlder.build();
        
        
        return explicitObject.toString();
		
		
	}

**Comment by telsethag** [comment]
@ericstephan @bibiraju Ah, ok thanks for showing the code, I see what's happening now.  This shouldn't be necessary becasuse the ProvenMessage constructor extracts the meta-data into the KnowledgeClass (for both measurement and explicit), right?  The message content for the new KnowledgeMessage classes would be just the raw message (i.e. w/o meta-data).

**Comment by ericstephan** [comment]
@telsethag<mailto:notifications@github.com>, @bibiraju

>> Ah, ok thanks for showing the code, I see what's happening now. This shouldn't be necessary becasuse the ProvenMessage constructor extracts the meta-data into the KnowledgeClass (for both measurement and expli cit), ri ght?


Yes exactly!  I kept getting into trouble when I was attempting to translate the raw message to early.  I have a couple of slides that illustrate my understanding of this at today's meeting.

Eric
________________________________
