### ISSUE TITLE
Blazegraph data ListMeasureables.py script creates inconsistent number of measurements

### ISSUE THREAD

**Issue by tonya1** [GRIDAPPSD/GOSS-GridAPPS-D#804]
### Description of Issue

After loading the xml files in the blazegraph container, for each feeder, the measurements are queried.   The ListMeasureables.py script producces inconsistent number of measurements. 

### Affected Version
fafc9d5

### Screenshots

for i in $( seq 5 ) ; do ./test_blazegraph.sh; done

timestamp    : git hash: rangeCount: line count of output *.txt files
190114161652 : fafc9d5 : 975616    : 37022
190114161735 : fafc9d5 : 975616    : 37017
190114161817 : fafc9d5 : 975616    : 37022
190114161904 : fafc9d5 : 975616    : 37010
190114161950 : fafc9d5 : 975616    : 37010

Here is the bash code I am using to pull the measurements from blazegraph

#TEST echo " "
#TEST echo "Generating measurements files"
python3 ../ListFeeders.py | grep -v 'binding keys' | while read line; do
  #TEST echo "  Generating measurements files for $line"
  python3 ../ListMeasureables.py $line
done

echo -n "$TIMESTAMP2 : $GITHASH : $rangeCount : "
wc -l *txt | grep total | awk '{print $1}'

**Comment by temcdrm** [comment]
Latest update to [PR 106](https://github.com/GRIDAPPSD/Powergrid-Models/pull/106) seems to resolve this. The _FlatPhases_ function appeared to produce inconsistent results because the SPARQL group concatenation does not preserve order.
