### ISSUE TITLE
GOSS class "get_response" method interferes with previous subscriptions

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#808]
@blthayer commented on [Sat Sep 29 2018](https://github.com/GRIDAPPSD/gridappsd-python/issues/1)

@craig8 
Note sure if this is an intentional design decision, but the way the `GOSS` class is written now, it doesn't work to have multiple subscriptions. 

## Problem
Here's what I ran into:
1. Subscribe to topic A, expecting this to keep going for as long as my `GOSS` instantiation is around.
2. Call `get_response` for topic B. 
3. Notice that we're no longer subscribed to topic A.

## Root cause
After investigating, this is because of the following sequence of events:
- `GOSS.subscribe` calls `GOSS._make_connection`
- `GOSS._make_connection` assigns to the class property, `GOSS._conn`
-  `GOSS.get_response` call `GOSS.subscribe`, thus overriding `GOSS._conn` with a new topic

## Proposed solution
The `GOSS` class should spin up a thread for each subscription, and each thread should have its own connection. In some cases, the thread could be long lived (like subscribing to subscription output). In other cases, the thread would be short lived (like calling `get_response` 

---

@blthayer commented on [Wed Nov 14 2018](https://github.com/GRIDAPPSD/gridappsd-python/issues/1#issuecomment-438842767)

@craig8 - any update on this?

---

@blthayer commented on [Tue Jan 15 2019](https://github.com/GRIDAPPSD/gridappsd-python/issues/1#issuecomment-454452788)

@craig8 - We talked about this a while ago, where did we leave it?

My understanding is that you can still only use a GridAPPSD object on one topic at a time, because any subsequent calls to `get_response` or `subscribe` override previous connections.

**Comment by craig8** [comment]
@blthayer I don't believe this is an issue.  See the following test code to see if you get an error or not.  If this is not the case then please provide an easy method for me to replicate your issue.

````
import json
from time import sleep

from gridappsd import GOSS


def get_response_example(goss_client):

    def addem_callback(header, message):
        # print("Addem callback")
        # print("Threadid: {}".format(threading.get_ident()))
        item = json.loads(message)
        total = 0
        for x in item:
            total += x

        reply_to = header['reply-to']
        goss_client.send(reply_to, str(total))


    gen_sub = []

    def generic_subscription(header, message):
        # print("Generic subscripton here!")
        # print("Threadid: {}".format(threading.get_ident()))
        gen_sub.append((header, message))
        #print("Gensub is {}".format(gen_sub))

    # Simulate an rpc call.
    goss_client.subscribe("/addem", addem_callback)

    # Simulate generic pubsub response
    goss_client.subscribe("/foo", generic_subscription)

    id_before = id(goss_client._conn)
    result = goss_client.get_response('/addem', json.dumps([5, 6]))
    assert result == 11
    assert id_before == id(goss_client._conn)
    #print("Threadid: {}".format(threading.get_ident()))
    #print(goss_client._conn.transport.listeners)
    goss_client.send("/foo", str(result))

    count = 0
    while True:
        sleep(0.1)
        count += 1
        if len(gen_sub) > 0 or count > 10:
            break

    assert gen_sub
    assert len(gen_sub) == 1
    # make sure the correct message was sent back
    assert int(gen_sub[0][1]) == 11
    assert result == 11


if __name__ == '__main__':
    goss = GOSS()
    get_response_example(goss)
````

**Comment by blthayer** [comment]
@craig8 - I was able to run your code successfully (without errors). If you're confident that this proves that I was experiencing a different issue when I filed this, I'm happy to close this issue.
