### ISSUE TITLE
Write the code that generate the out station points 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#822]
From the model_dict.json create all the control points and all measurement point for dnp3 outstation

**Comment by poorva1209** [comment]
Create a repo in GridAPPS-D organization and push updates.

**Comment by singha42** [comment]
The dnp3 points for all the measurements and control points are created using the model dictionary file. The code will be uploaded in gridappsd-dnp3 repo.

**Comment by singha42** [comment]
Example of a control point : 

{
      "attribute": "ShuntCompensator.aVRDelay", 
      "data_type": "AI", 
      "description": "Capacitor, cap2,phase -C", 
      "group": 32, 
      "index": 7, 
      "name": "cap2", 
      "object_id": "_F151E337-356D-D7AB-9215-8BCBDFEC5315", 
      "variation": 3
    }, 

{
      "attribute": "TapChanger.lineDropX", 
      "data_type": "AI", 
      "description": "Regulator, reg1 phase is  -  A", 
      "group": 32, 
      "index": 23, 
      "name": "Reg", 
      "object_id": "_0C9004C7-026D-FEA2-A31E-EF5D50884C05", 
      "variation": 3
    }, 
    {
      "attribute": "TapChanger.lineDropX", 
      "data_type": "AI", 
      "description": "Regulator, reg2 phase is  -  B", 
      "group": 32, 
      "index": 24, 
      "name": "Reg", 
      "object_id": "_C5C2E4D0-2694-0FBF-5822-8BA77A0F39C4", 
      "variation": 3
    }, 

Example of a measurement points:

 {
      "data_type": "AO", 
      "description": "Equipment is PowerTransformer_sub3_Power,PowerTransformer and phase is C", 
      "group": 42, 
      "index": 43, 
      "measurement_id": "_5033057d-1da3-4ead-ab98-c382ca782114", 
      "measurement_type": "VA", 
      "name": "PowerTransformer_sub3_Power", 
      "variation": 3
    },

**Comment by singha42** [comment]
Code uploaded in gridappsd-dnp3 repo.
