### ISSUE TITLE
Add unit context in weather data in PROVEN/Influxdb

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#824]

**Comment by ericstephan** [comment]
@tdtalbot and I created a preliminary reference model for the solar weather station.  I submitted a pull request yesterday.  @poorva1209 @tonya1

**Comment by poorva1209** [comment]
@ericstephan @tonya1 I am putting this in backlog as if the pull request is merged, it will need changes in weather converter file that we don't have the bandwidth to do in this sprint.
