### ISSUE TITLE
fncs_goss_bridge error when running IEEE 13-node model

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#831]
### Description of Issue
When running a simulation of the IEEE 13 bus case, the fncs_goss_bridge throws exceptions, and thus simulation output doesn't seem to make it out of the simulation. There's also possibly a Proven error in here.

### Affected Version
`develop` tag.

### Steps to Reproduce
1. Start the platform.
2. Navigate to the platform in your web browser, select simulations, and select `ieee13nodeckt` in the `Line name` drop-down.
3.  Hit `Submit`
4. In the next page, hit `Start Simulation`
    - It's worth noting here that the viz is broken here, in that what you see in no way resembles a feeder. It's just a hodge-podge of symbols on top of each other.
5. In the terminal which you started the platform, notice there seem to be some problems:

```
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : object name '1648537166' does not follow strict naming rules and may not link correctly during load time
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : last warning message was repeated 16 times
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : connection: local variable '650z.voltage_A' cannot be resolved. This local variable will not be publish.
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : last warning message was repeated 6 times
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : 0, fncs_msg::init(): vjson_publish_gld_property 611.voltage_C not initialized!:  
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: 
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : last warning message was repeated 146 times
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : fncs_msg::init(): 1648537166 is deferring initialization.
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : Node:cap_cap1 does not have the same nominal voltage as its parent - copying voltage from parent.
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : last warning message was repeated 1 times
Thread-63 INFO [gov.pnnl.goss.gridappsd.simulation.SimulationProcess] - Simulator: WARNING  [INIT] : connection: local variable '650z.voltage_A' cannot be resolved. This local variable will not be publish.
```

6. In the terminal, notice the following error after the 5th time step:

```
Thread-39 ERROR [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1548949712000|fncs_goss_bridge.py|1648537166|ERROR|system|ERROR
Error on get FncsBusMessages for 1648537166 Traceback (most recent call last):
  File "/gridappsd/services/fncsgossbridge/service/fncs_goss_bridge.py", line 584, in _get_fncs_bus_messages
    prop_val_str = gld_properties_dict.get(property_name, None)
AttributeError: 'NoneType' object has no attribute 'get'
```

    This error repeats every few time steps.

7. Wait for the simulation to complete, grab its simulation ID.
8. Go the the `stomp client` tab in the viz.
    1. Change topic to `goss.gridappsd.process.request.data.timeseries`
    2. Paste the following into the request window (update the `simulationId`):

```
{"queryMeasurement": "PROVEN_MEASUREMENT", "queryFilter": {"hasSimulationId": "1877140527"}, "responseFormat": "JSON"}
```

    3. Hit `send request`
    4. The response will look something like:

```
{ "data": { "measurements": [ { "points": [] } ] }, "responseComplete": true, "id": "1400487533" }
```

    5. Notice in the terminal you get the following message:

```
LOOKING FOR CONVERTER PROVEN_PROVEN_MEASUREMENT:JSON  IN   {PROVEN_WEATHER:GRIDLABD_WEATHER=gov.pnnl.goss.gridappsd.data.conversion.ProvenWeatherToGridlabdWeatherConverter@43298428}
Thread-41 WARN [gov.pnnl.goss.gridappsd.log.LogManagerImpl] - 1548950754816|gov.pnnl.goss.gridappsd.data.DataManagerImpl|0|RUNNING|system|WARN
No Data converter available for PROVEN_PROVEN_MEASUREMENT to JSON
```

### Summary
1. fncs_goss_bridge error when running IEEE 13 bus model.
2. viz isn't properly functioning for the IEEE 13 bus model.
3. There's some sort of Proven issue.

Are there actually measurement objects in the IEEE 13 bus model?

**Comment by poorva1209** [comment]
@blthayer 
- It seems like influxdb contains no data in it. Get outside containers and go into gridappsd -docker folder, Execute following command:
       1. docker pull gridappsd/influxdb:develop
       2. run.sh -t develop
- We are aware that Proven either doesn't return or returns a subset of simulation data after query. We already have a fix for it and will released by Monday next week. 
- For Viz issue with 123 model, I will create a saperate issue and assign to @bibiraju . She might need you to exaplain the issue in detail.

Let me know if after influxdb pull you are still not able to run a simulation without error.

**Comment by blthayer** [comment]
@poorva1209 

- I've pulled the `develop` container for influxdb. **I still get the `fncs_goss_bridge` error**. I did confirm that there is at least some weather data in the database.
- Sounds good, I'll keep an eye out for that.
- I've commented on the viz 13-bus model issue.

Another note:

**Comment by afisher1** [comment]
I ran the IEEE13nodeckt from the latest develop of everything. I can confirm that there is measurement data in the blazegraph model as there is measurements present in the model_dict.json file and in the model_outupts.json file. However, there is an error occurring because the Bridge is reporting missing voltage measurements for an object named 650z. This is the connectivity node for the substation transformer, xf_sub3.  Looking in the model_base.glm, the from node for xf_sub3 is called sourcebus.  I don't know how to explain this discrepancy in the glm file and the CIM model. @temcdrm do you have any ideas.

**Comment by afisher1** [comment]
Alright I talked with Tom and found out the issues is because for testing perposes Tom made the Substation trasnformer in the 13 node CIM model be a delta configured xf with a tertiary winding. 650z is the tertiary node. GLD doesn't support tertiary winding xformers so it just leaves out the 650z node in the model. hence why the bridge is warning us about missing measurements for node 650z. The message in the bridge is a warning and should stay a warning but the bridge should also not try to get those measurements after it has determined that those measurements are missing. It is currently trying to grab those measurements which creates a python exception. I'm fixing the bridge to not try to grab the missing measurements.

**Comment by blthayer** [comment]
@afisher1, @poorva1209 - I can confirm that Andy fixed the 13-node issues I was encountering. However, I'm still not getting anything out of Proven. I'll close this one and file one specific to the Proven issue.
