### ISSUE TITLE
Messed up symbols in 13 model

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#832]
@blthayer Brandon reported this issue: 

Viz is broken for 13 mode display. What you see in no way resembles a feeder. It's just a hodge-podge of symbols on top of each other.

**Comment by bibiraju** [comment]
@poorva1209  @blthayer Is it for 123 or 13 node?

**Comment by poorva1209** [comment]
Oh its for 13 node model. I changed the description.

**Comment by poorva1209** [comment]
@blthayer Can you check and close this issue.

**Comment by blthayer** [comment]
@poorva1209 - I checked, and things look better. There's still some weirdness (not everything is connected), but it's certainly better than what it was before.
