### ISSUE TITLE
Measurements image missing in documentation

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#837]
### Description of Issue
UML diagram for measurements missing in Read the Docs.

https://gridappsd.readthedocs.io/en/latest/developer_resources/index.html#cim-documentation

Do a search for "Figure 12:" and notice the image this caption refers to isn't being rendered (probably due to a syntax error or bad filepath in the source).

**Comment by blthayer** [comment]
@temcdrm - this image is still missing.

**Comment by temcdrm** [comment]
This was a case sensitivity problem in the file name, affecting only Linux build.  Poorva or Craig, please trigger a rebuild on RTD if necessary.

**Comment by craig8** [comment]
Looks like it has been rebuilding as people are committing because I didn't trigger any of these.

![image](https://user-images.githubusercontent.com/3979063/53438536-f4795680-39b4-11e9-86c6-00ac34bc0af7.png)
