### ISSUE TITLE
Process simulation input message with command key 

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#842]
Changes in 
- [ ] fncs goss bridge
- [ ] gridappsd-python

**Comment by craig8** [comment]
@poorva1209 command and input keys are a necessary level abstraction.  This is the header of the message that the bridge uses to determine routing information.  It is not part of the api specifically.  @afisher1 and @craig8 discussed and there is really no reason for this information to go to the output.

**Comment by craig8** [comment]
Also there is an output key in the bridge but @afisher1 doesn't ever send the dictionary at that level so that it "looks" like what is in the documentation.  https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/blob/master/services/fncsgossbridge/service/fncs_goss_bridge.py#L198

**Comment by poorva1209** [comment]
Not needed.

**Comment by poorva1209** [comment]
Re-opening it to resolve input message processing issue in proven.
