### ISSUE TITLE
No measurement data in Proven after running simulations.

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#856]
### Description of Issue
After running a simulation and then querying the platform for measurements, no data is returned. This is true for both the 13 node and 8500 node circuits (I haven't tested others).

### Affected Version
`develop` tag when running the platform.

#### Expected
After running a simulation, there should be accessible measurement data in the database.

#### Actual
The data return is empty.

### Steps to Reproduce
1. Start platform (with `develop` tag).
2. Run simulation through viz. 
    - Select either `ieee13nodeckt` or `ieee8500` from the `Line name` dropdown
    - Change duration to something shorter, like `20` seconds
    - Hit `Submit`
    - Hit `Start Simulation`
3. Wait for the simulation to run all the way through, copy the simulation ID from the terminal
4. Navigate to the `Stomp Client` in the browser.
    - Update topic to `goss.gridappsd.process.request.data.timeseries`
    - Copy + paste the following into the request area, update simulation ID.
    ```
    {"queryMeasurement": "PROVEN_MEASUREMENT",
     "queryFilter": {"hasSimulationId": "1877140527"},
     "responseFormat": "JSON"}
    ```
    - Hit `send request`
    - Notice the response is empty:
    ```
    { "data": { "measurements": [ { "points": [] } ] }, "responseComplete": true, "id": "1549151384" }
    ```
5. Repeat steps 2-4 with the other model, notice the results are the same.

@poorva1209 @ericstephan

**Comment by blthayer** [comment]
Update:

I went to test this today, and am getting a new (still empty) return:

```
{
    "data": null,
    "responseComplete": true,
    "id": "1575560134"
}
```

@poorva1209 - is this on the docket to fix soon? It's been blocking me for quite some time (I had also mentioned this back in January in [issue 831](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/issues/831)).

**Comment by poorva1209** [comment]
This shouldn't be happening anymore. Let me check, I will back to you today.

**Comment by blthayer** [comment]
> This shouldn't be happening anymore. Let me check, I will back to you today.

@poorva1209 - any luck?

**Comment by poorva1209** [comment]
I can reproduce it. Checking it now.

**Comment by poorva1209** [comment]
I figured out the issue. Working with PROVEN team to team to resolve it.

**Comment by poorva1209** [comment]
Just wanted to add notehere: data was there in proven but Query API in timeseries data manager and Proven was not updated.
