### ISSUE TITLE
Review Conceptual design documentation

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#867]

**Comment by jpo2101** [comment]
[GridAppsD Platform Conceptual Design V1.0 JPO Comments.docx](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/2998720/GridAppsD.Platform.Conceptual.Design.V1.0.JPO.Comments.docx)

[GridAppsD Platform Conceptual Design V1.0 JPO Comments.docx](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/2998727/GridAppsD.Platform.Conceptual.Design.V1.0.JPO.Comments.docx)
