### ISSUE TITLE
Review functional requirements documentation

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#868]

**Comment by jpo2101** [comment]
General comments:
[Functional Specifications Review -JPO.pdf](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/3004920/Functional.Specifications.Review.-JPO.pdf)

Comments embedded in document:
[Functional Specification for GridAPPS-D -JPO review.docx](https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/files/3004919/Functional.Specification.for.GridAPPS-D.-JPO.review.docx)
