### ISSUE TITLE
have all services be part of the default docker 

### ISSUE THREAD

**Issue by afisher1** [GRIDAPPSD/GOSS-GridAPPS-D#874]
### Description of Issue
Right now not all the services are being included in the GridAPPS-D Platform Docker image by default. Rather than instructing Application developers to modify the docker installation files to include services they need we should be supplying all the services in the plaform by default.

services that need to be added:

- sensor service

- state estimator service

### Affected Version
all versions
### Screenshots
NA
#### Expected
NA
#### Actual
NA
### Steps to Reproduce
NA
### Additional Details
NA

**Comment by poorva1209** [comment]
Following services are part of gridappsd docker : 
- sensor service
- voltage violation service

Similarly state-estimator would be added once it is ready. Closing this issue.
