### ISSUE TITLE
Establish Operator Test Use Case for Survalent

### ISSUE THREAD

**Issue by areiman** [GRIDAPPSD/GOSS-GridAPPS-D#924]
We need to establish the use case of Survalent for the application evaluations.

Specifically, will it be useful to have a SCADA implementation of Survalent without being able to use Survalent apps?

**Comment by areiman** [comment]
Discussion was initiated with Jon Barr on 5/28.

**Comment by poorva1209** [comment]
Control capacitors and regulators.

**Comment by singha42** [comment]
@poorva1209 :Tested the 9500 model. The plot  in the Viz is showing the control changes for switches but the switch color is not changing from Red to Green when "ON".

**Comment by singha42** [comment]
Tested all the points except the Analog measurements as suggested by Tom. It is working as expected.
