### ISSUE TITLE
Houses are not present in IEEE 8500 node model

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#937]
@poorva1209 @tonya1 @temcdrm 
Should they be?

Currently, trying to run a simulation and changing ` "use_houses": false` to ` "use_houses": true` does not put the houses in the model. This can be proven by doing the following _after_ starting the simulation:
1. Use `docker exec -it <container ID> /bin/bash` to get into the running gridappsd container
2. `cd /tmp/gridappsd_tmp/<simulation ID>`
3. `cat model_base.glm | grep house`
4. Use the above cat command on all files in that directory. You'll get no results.

The houses are also not in blazegraph. Prove this by navigating to http://localhost:8889/bigdata/#query and running the following query (that feeder ID is for the 8500 node model):

```

# list houses - DistHouse
PREFIX r:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX c:  <http://iec.ch/TC57/CIM100#>
SELECT ?fdrname ?name ?parent ?coolingSetpoint ?coolingSystem ?floorArea ?heatingSetpoint ?heatingSystem ?hvacPowerFactor ?numberOfStories ?thermalIntegrity ?id ?fdrid 
WHERE { 
#	VALUES ?fdrid {"_9CE150A8-8CC5-A0F9-B67E-BBD8C79D3095"}
	VALUES ?fdrid {"_4F76A5F9-271D-9EB8-5E31-AA362D86F2C3"}
   ?h r:type c:House.
   ?h c:IdentifiedObject.name ?name.
   ?h c:IdentifiedObject.mRID ?id.
   ?h c:House.floorArea ?floorArea.
   ?h c:House.numberOfStories ?numberOfStories.
   OPTIONAL{?h c:House.coolingSetpoint ?coolingSetpoint.}
   OPTIONAL{?h c:House.heatingSetpoint ?heatingSetpoint.}
   OPTIONAL{?h c:House.hvacPowerFactor ?hvacPowerFactor.}
   ?h c:House.coolingSystem ?coolingSystemRaw.
   	bind(strafter(str(?coolingSystemRaw),"HouseCooling.") as ?coolingSystem) 
   ?h c:House.heatingSystem ?heatingSystemRaw.
   	bind(strafter(str(?heatingSystemRaw),"HouseHeating.") as ?heatingSystem)
   ?h c:House.thermalIntegrity ?thermalIntegrityRaw.
   	bind(strafter(str(?thermalIntegrityRaw),"HouseThermalIntegrity.") as ?thermalIntegrity)
   ?h c:House.EnergyConsumer ?econ.
   ?econ c:IdentifiedObject.name ?parent.
   ?fdr c:IdentifiedObject.mRID ?fdrid.
   ?fdr c:IdentifiedObject.name ?fdrname.
   ?econ c:Equipment.EquipmentContainer ?fdr.
} ORDER BY ?fdrname ?name
```

**Comment by blthayer** [comment]
Update: After talking with @temcdrm at the standup this morning, we think that during the docker image build pipeline, some variant of [test.sh](https://github.com/GRIDAPPSD/Powergrid-Models/blob/develop/houses/test.sh) should be run to put houses on all available models. Note that the final numeric input to [insertHouses.py](https://github.com/GRIDAPPSD/Powergrid-Models/blob/master/houses/insertHouses.py) denotes a climate zone, as documented in the "main" section of the code.

Since the `"use_houses"` flag for running simulations defaults to `false`, this shouldn't impact anyone using the default options. 

Tagging @tdtalbot as I understand she's involved in the blazegraph build pipeline.

**Comment by tonya1** [comment]
Verified houses are present in the v2019.06.0 blazegraph container using the included query.
