### ISSUE TITLE
Viz bugs

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#938]
- [x] Line name is not based on previously selected values.
- [x] Removing a selected app-name closes input form
- [x] Change Event Id to Event tag
- [ ] Change attribute to a multi-value select box
- [x] Help-text 'Add input item' does not go away on CommOutage tab
- [x] Object mrid is not correct for multiple phases selection (maybe because capacitor has the same mrid for different phases)

**Comment by nhuyvan** [comment]
The checked items were fixed in https://github.com/GRIDAPPSD/gridappsd-viz/pull/93

**Comment by nhuyvan** [comment]
First checkbox was fixed here https://github.com/GRIDAPPSD/gridappsd-viz/pull/96
