### ISSUE TITLE
Switch position measurements not present in 8500 node model

### ISSUE THREAD

**Issue by blthayer** [GRIDAPPSD/GOSS-GridAPPS-D#961]
**Platform tag: v2019.06.0**
## Problem
It would appear there are no "discrete" position measurements in the 8500 model for LoadBreakSwitches. Here's a simple query to prove it:
```sparql
PREFIX r:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX c:  <http://iec.ch/TC57/CIM100#>
SELECT ?switch_mrid ?switch_meas_mrid ?type
WHERE {
    VALUES ?feeder_mrid {"_4F76A5F9-271D-9EB8-5E31-AA362D86F2C3"}
    ?eq c:Equipment.EquipmentContainer ?fdr .
    ?fdr c:IdentifiedObject.mRID ?feeder_mrid .
    # { ?s r:type c:Discrete. }
    ?s r:type ?type .
    ?s c:IdentifiedObject.mRID ?switch_meas_mrid .
    ?s c:Measurement.PowerSystemResource ?eq .
    ?s c:Measurement.Terminal ?trm .
    ?eq c:IdentifiedObject.mRID ?switch_mrid .
    ?eq r:type c:LoadBreakSwitch .
}
ORDER BY ?switch_mrid
```
Here's a small subset of the results (sorry for the mediocre formatting):
```

switch_mrid | switch_meas_mrid | type
-- | -- | --
_02FFFE21-AFE1-E575-20AA-4515E024ED5B | _0667ba03-8fe0-4a33-ab9c-cc82d2b14293 | <http://iec.ch/TC57/CIM100#Analog>
_02FFFE21-AFE1-E575-20AA-4515E024ED5B | _c9445e06-7e11-4738-827f-446cd356e647 | <http://iec.ch/TC57/CIM100#Analog>
_02FFFE21-AFE1-E575-20AA-4515E024ED5B | _5eee7abf-1dbe-43dc-a110-77ebf91a11d1 | <http://iec.ch/TC57/CIM100#Analog>
_044C1F8D-A4B8-2219-3EC1-4F47FE249755 | _c05fa348-e963-4cb1-a0f9-16f28dda76af | <http://iec.ch/TC57/CIM100#Analog>
_044C1F8D-A4B8-2219-3EC1-4F47FE249755 | _ec5108a2-ae2a-414a-b41d-73e8261a402d | <http://iec.ch/TC57/CIM100#Analog>


```
In the results, notice that the `?type` variable is **only** Analog. If you uncomment the line in there which forces the type to be discrete, you'll get no results.
## Implications
Without these discrete measurements, it becomes much more difficult for application developers to determine the status of a switch. We'd like to simply listen to position (open/closed) measurements, and update our internal models accordingly. Instead, we would have to track multiple voltage measurements for each switch, and compare voltages on both ends to determine whether or not the switch is open. While this is feasible, it's probably 4x the work.
## Solution
In the process which adds measurements to objects, add discrete position measurements to each switch, similar to how capacitors have this measurement.

## Tagging for attention
@afisher1 @poorva1209 @tonya1 @temcdrm - please reassign as needed.

**Comment by poorva1209** [comment]
Tom suggested looking for 'current' measurement for that switch. If it is 0 then switch os open else close. 
does that solve your issue?

**Comment by blthayer** [comment]
@poorva1209 - that's not a bad proxy/work-around, but still results in more work (topology processing/tree tracing) for every app developer: if an upstream switch is open, all downstream switches will look open (because no current will be flowing) as well. Then, when that upstream switch closes again, you have to check the whole tree.

**Comment by poorva1209** [comment]
We are adding the position measurements in the model.

**Comment by temcdrm** [comment]
- Just pushed change to InsertMeasurements.py in the powergrid-models develop branch

- The platform measurement insertion scripts have to be re-run now.

**Comment by blthayer** [comment]
@poorva1209 @tonya1 

I can confirm that the discrete measurements are in blazegraph when using the `develop` tag.
