### ISSUE TITLE
viz display when no access to internet

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#965]
The display becomes unusable if the viz is run without that container having access to the internet.  Steps to reproduce
 
 1. Launch ./run.sh from gridappsd-docker
 1. unplug network
 1. open browser to the localhost:8080

The googleapi fonts and styling are not able to be downloaded and therefore the app becomes unusable.

A good fix would be when building the container to download those fonts to the local container (unless there is a licensing reason not to)

**Comment by nhuyvan** [comment]
@bibiraju https://github.com/GRIDAPPSD/gridappsd-viz/pull/109
