### ISSUE TITLE
viz assumes localhost in resonse to client

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#966]
When stomp.js and the various pages are sent to the client, an embedded localhost or 127.0.0.1 is sent to the client, whether the client is actually on the same host as the server.  In the code this happens inside the runConfig.ts 

````
export const RUN_CONFIG = {
  "version": "develop",
  "gossServerUrl": "ws://127.0.0.1:61614"
};
````

In the webpack.config.js file

````
function writeVersionNumber(versionNumber) {
  const runConfig = 'export const RUN_CONFIG = ' + JSON.stringify({
    "version": versionNumber,
    "gossServerUrl": "ws://127.0.0.1:61614"
  }, null, 2) + ';\n';
````

Changing these two spots to have a resolvable hostname (from the client's perspective) allows access to the server from external clients.

**Comment by nhuyvan** [comment]
@bibiraju https://github.com/GRIDAPPSD/gridappsd-viz/pull/110
@tonya1 Tonya, please see the above PR, you probably have to change your docker script to specify the build version number

**Comment by nhuyvan** [comment]
@bibiraju https://github.com/GRIDAPPSD/gridappsd-viz/pull/111
