### ISSUE TITLE
Transform survalent xml to CIM100

### ISSUE THREAD

**Issue by poorva1209** [GRIDAPPSD/GOSS-GridAPPS-D#968]
- Find a resource.
- It is CIM14
- Is there an online website to do that? - Not as specific may be.
- automate the process. 

Tom: Does Survalent take any other model, other than CIM? ESRI?
Jeff will ask around for a process. 

https://www.freeformatter.com/xsl-transformer.html

**Comment by temcdrm** [comment]
Issue 1029 supercedes this.  We don't actually need to import CIM14.
