### ISSUE TITLE
Test Configuration Issues

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#981]
Bouncing balls are set when going directly to the Test Configuration tab (without selecting the line).  Then after selecting line in Power System Configuration tab the bouncing balls may or may not be there.  I think that the time for the 9500 node model to load may be why the bouncing balls may be there and I didn't leave enough time.

![image.png](https://images.zenhubusercontent.com/55b9aef64f7a08fbb7f3fd50/8bb517df-2cdc-4bad-a3c4-897a5a1a657e)

**Comment by bibiraju** [comment]
We need to know the line name to pre-populate some items in test configuration. But instead of the bouncing balls, we can display a message asking the user to select a line name if not selected already.

**Comment by poorva1209** [comment]
@bibiraju Yeah that would be a better message.

**Comment by nhuyvan** [comment]
https://github.com/GRIDAPPSD/gridappsd-viz/pull/125
