### ISSUE TITLE
simulation.output.<simulationid> is not being published to

### ISSUE THREAD

**Issue by craig8** [GRIDAPPSD/GOSS-GridAPPS-D#989]
This either needs to be added to the SimulationProcess or the fncsgoss bridge.  I am going to add it to the fncsgoss bridge because it is more straight forward to publishe 2x once on the fncs topic and once on the other topic.

**Comment by poorva1209** [comment]
fncsgossbridge already publishes simulation output at simulation.output.[simId] topic on line 225 (link below). It does not publish simulation output on fncs output topic. Only communication needed between simulation manager and fncs bridge happens on fncs input/output topics, not simulation output. 

https://github.com/GRIDAPPSD/GOSS-GridAPPS-D/blob/dd107993dbe57fd01bf07bbeba2a7d795afe9df3/services/fncsgossbridge/service/fncs_goss_bridge.py#L225.
